
; ASM FILE code\common\scripting\text\unused_textfunctionsdata.asm :
; 0x6D74..0x6E94 : Unused text functions data
                dc.b 0                  ; unused data
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $E
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $EC
                dc.b $CB
                dc.b $BB
                dc.b $BB
                dc.b $EC
                dc.b $BE
                dc.b $CB
                dc.b $11
                dc.b $EC
                dc.b $BC
                dc.b $B1
                dc.b $CC
                dc.b $EC
                dc.b $BB
                dc.b $1C
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $EE
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $BB
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $11
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $CC
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
                dc.b $EC
                dc.b $B1
                dc.b $CD
                dc.b $DD
