
; SCRIPT SECTION maps\entries\map06\mapsetups\s1 :
; 
ms_map6_Entities:   dc.b $12
										dc.b $19
										dc.b 1
										dc.b 7
										dc.l eas_46212          
										dc.b $14
										dc.b $17
										dc.b 3
										dc.b $C1
										dc.l eas_Init2          
										dc.b $12
										dc.b 8
										dc.b 3
										dc.b $C9
										dc.b $FF
										dc.b $12
										dc.b 8
										dc.b 1
										dc.b $10
										dc.b $17
										dc.b 3
										dc.b $C3
										dc.l eas_Init2          
										dc.b $F
										dc.b $19
										dc.b 0
										dc.b $C3
										dc.l eas_Init2          
										dc.b $F
										dc.b $18
										dc.b 0
										dc.b $C0
										dc.l eas_Init2          
										dc.b $12
										dc.b $17
										dc.b 3
										dc.b $C1
										dc.l eas_Init2          
										dc.b $11
										dc.b $17
										dc.b 3
										dc.b $C6
										dc.l eas_Init2          
										dc.b $E
										dc.b $1A
										dc.b 0
										dc.b $CA
										dc.l eas_Init2          
										dc.b $10
										dc.b $19
										dc.b 0
										dc.b $C8
										dc.l eas_Init2          
										dc.b $15
										dc.b $19
										dc.b 2
										dc.b $C8
										dc.l eas_Init2          
										dc.b $A
										dc.b $C
										dc.b 0
										dc.b $CA
										dc.l eas_Init           
										dc.b $B
										dc.b $C
										dc.b 2
										dc.b $CE
										dc.l eas_Init           
										dc.b $13
										dc.b $1C
										dc.b 1
										dc.b $C8
										dc.l eas_Init2          
										dc.b $E
										dc.b $1B
										dc.b 0
										dc.b $E2
off_5486C:          dc.l eas_Init2          
										dc.b $3F
										dc.b $3F
										dc.b 0
										dc.b $C6
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 0
										dc.b $C6
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $CD
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.w $FFFF
