

; ---------------------------------------------------------------------------

; enum Extended Status Screen VdpTiles (bitfield)
    if (STANDARD_BUILD&EXTENDED_STATUS=1)
VDPTILE_ELEMENT_WIND: equ 1
VDPTILE_ELEMENT_LIGHTNING: equ 2
VDPTILE_ELEMENT_ICE: equ 3
VDPTILE_ELEMENT_FIRE: equ 4
VDPTILE_ELEMENT_HIDDEN: equ 7
VDPTILE_ELEMENT_STATUS: equ 8
    endif

; ---------------------------------------------------------------------------

; enum VdpTiles_General (bitfield)
VDPTILE_SPACE: equ $20
VDPTILE_EXCLAMATION_MARK: equ $21
VDPTILE_QUOTATION_MARK: equ $22
VDPTILE_NUMBER_SIGN: equ $23
VDPTILE_DOLLAR_SIGN: equ $24
VDPTILE_PERCENT_SIGN: equ $25
VDPTILE_AMPERSAND: equ $26
VDPTILE_APOSTROPHE: equ $27
VDPTILE_OPENING_ROUND_BRACKET: equ $28
VDPTILE_CLOSING_ROUND_BRACKET: equ $29
VDPTILE_MULTIPLICATION_SIGN: equ $2A
VDPTILE_PLUS_SIGN: equ $2B
VDPTILE_COMMA: equ $2C
VDPTILE_MINUS_SIGN: equ $2D
VDPTILE_DOT: equ $2E
VDPTILE_SLASH: equ $2F
VDPTILE_NUMBER_0: equ $30
VDPTILE_NUMBER_1: equ $31
VDPTILE_NUMBER_2: equ $32
VDPTILE_NUMBER_3: equ $33
VDPTILE_NUMBER_4: equ $34
VDPTILE_NUMBER_5: equ $35
VDPTILE_NUMBER_6: equ $36
VDPTILE_NUMBER_7: equ $37
VDPTILE_NUMBER_8: equ $38
VDPTILE_NUMBER_9: equ $39
VDPTILE_COLON: equ $3A
VDPTILE_SEMICOLON: equ $3B
VDPTILE_LESS_THAN_SIGN: equ $3C
VDPTILE_EQUALS_SIGN: equ $3D
VDPTILE_GREATER_THAN_SIGN: equ $3E
VDPTILE_QUESTION_MARK: equ $3F
VDPTILE_COPYRIGHT_SIGN: equ $40
VDPTILE_UPPERCASE_A: equ $41
VDPTILE_UPPERCASE_B: equ $42
VDPTILE_UPPERCASE_C: equ $43
VDPTILE_UPPERCASE_D: equ $44
VDPTILE_UPPERCASE_E: equ $45
VDPTILE_UPPERCASE_F: equ $46
VDPTILE_UPPERCASE_G: equ $47
VDPTILE_UPPERCASE_H: equ $48
VDPTILE_UPPERCASE_I: equ $49
VDPTILE_UPPERCASE_J: equ $4A
VDPTILE_UPPERCASE_K: equ $4B
VDPTILE_UPPERCASE_L: equ $4C
VDPTILE_UPPERCASE_M: equ $4D
VDPTILE_UPPERCASE_N: equ $4E
VDPTILE_UPPERCASE_O: equ $4F
VDPTILE_UPPERCASE_P: equ $50
VDPTILE_UPPERCASE_Q: equ $51
VDPTILE_UPPERCASE_R: equ $52
VDPTILE_UPPERCASE_S: equ $53
VDPTILE_UPPERCASE_T: equ $54
VDPTILE_UPPERCASE_U: equ $55
VDPTILE_UPPERCASE_V: equ $56
VDPTILE_UPPERCASE_W: equ $57
VDPTILE_UPPERCASE_X: equ $58
VDPTILE_UPPERCASE_Y: equ $59
VDPTILE_UPPERCASE_Z: equ $5A
VDPTILE_OPENING_SQUARE_BRACKET: equ $5B
VDPTILE_BACKSLASH: equ $5C
VDPTILE_CLOSING_SQUARE_BRACKET: equ $5D
VDPTILE_VERTICAL_ARROW: equ $5E
VDPTILE_UNDERSCORE: equ $5F
VDPTILE_CORNER: equ $60 ; window corner
VDPTILE_H_BORDER: equ $61 ; horizontal window border
VDPTILE_TRADEMARK_SYMBOL1: equ $62
VDPTILE_TRADEMARK_SYMBOL2: equ $63
VDPTILE_V_ARROW: equ $64 ; vertical arrow
VDPTILE_H_ARROW: equ $65 ; horizontal arrow
VDPTILE_ORANGE_LOWERCASE_A: equ $66
VDPTILE_ORANGE_LOWERCASE_B: equ $67
VDPTILE_ORANGE_LOWERCASE_C: equ $68
VDPTILE_ORANGE_LOWERCASE_D: equ $69
VDPTILE_ORANGE_LOWERCASE_E: equ $6A
VDPTILE_ORANGE_LOWERCASE_F: equ $6B
VDPTILE_ORANGE_LOWERCASE_G: equ $6C
VDPTILE_ORANGE_LOWERCASE_H: equ $6D
VDPTILE_ORANGE_LOWERCASE_I: equ $6E
VDPTILE_ORANGE_LOWERCASE_J: equ $6F
VDPTILE_V_BORDER: equ $70 ; vertical window border
VDPTILE_ORANGE_LOWERCASE_K: equ $71
VDPTILE_ORANGE_LOWERCASE_L: equ $72
VDPTILE_ORANGE_LOWERCASE_M: equ $73
VDPTILE_ORANGE_LOWERCASE_N: equ $74
VDPTILE_ORANGE_LOWERCASE_O: equ $75
VDPTILE_ORANGE_LOWERCASE_P: equ $76
VDPTILE_ORANGE_LOWERCASE_Q: equ $77
VDPTILE_ORANGE_LOWERCASE_R: equ $78
VDPTILE_ORANGE_LOWERCASE_S: equ $79
VDPTILE_ORANGE_LOWERCASE_T: equ $7A
VDPTILE_ORANGE_LOWERCASE_U: equ $7B
VDPTILE_ORANGE_LOWERCASE_V: equ $7C
VDPTILE_ORANGE_LOWERCASE_W: equ $7D
VDPTILE_ORANGE_LOWERCASE_X: equ $7E
VDPTILE_ORANGE_LOWERCASE_Y: equ $7F
VDPTILE_ORANGE_LOWERCASE_Z: equ $80
VDPTILE_LOWERCASE_A: equ $81
VDPTILE_LOWERCASE_B: equ $82
VDPTILE_LOWERCASE_C: equ $83
VDPTILE_LOWERCASE_D: equ $84
VDPTILE_LOWERCASE_E: equ $85
VDPTILE_LOWERCASE_F: equ $86
VDPTILE_LOWERCASE_G: equ $87
VDPTILE_LOWERCASE_H: equ $88
VDPTILE_LOWERCASE_I: equ $89
VDPTILE_LOWERCASE_J: equ $8A
VDPTILE_LOWERCASE_K: equ $8B
VDPTILE_LOWERCASE_L: equ $8C
VDPTILE_LOWERCASE_M: equ $8D
VDPTILE_LOWERCASE_N: equ $8E
VDPTILE_LOWERCASE_O: equ $8F
VDPTILE_LOWERCASE_P: equ $90
VDPTILE_LOWERCASE_Q: equ $91
VDPTILE_LOWERCASE_R: equ $92
VDPTILE_LOWERCASE_S: equ $93
VDPTILE_LOWERCASE_T: equ $94
VDPTILE_LOWERCASE_U: equ $95
VDPTILE_LOWERCASE_V: equ $96
VDPTILE_LOWERCASE_W: equ $97
VDPTILE_LOWERCASE_X: equ $98
VDPTILE_LOWERCASE_Y: equ $99
VDPTILE_LOWERCASE_Z: equ $9A
VDPTILE_ORANGE_EXCLAMATION_MARK: equ $9B
VDPTILE_ORANGE_QUOTATION_MARK: equ $9C
VDPTILE_ORANGE_NUMBER_SIGN: equ $9D
VDPTILE_ORANGE_DOLLAR_SIGN: equ $9E
VDPTILE_ORANGE_PERCENT_SIGN: equ $9F
VDPTILE_HORIZONTAL_ARROW: equ $A0
VDPTILE_STATUSEFFECT_ATTACK1: equ $A1 ; left half of icon
VDPTILE_STATUSEFFECT_ATTACK2: equ $A2 ; right half of icon
VDPTILE_STATUSEFFECT_BOOST1: equ $A3 ; left half of icon
VDPTILE_STATUSEFFECT_BOOST2: equ $A4 ; right half of icon
VDPTILE_HYPHEN: equ $A5
VDPTILE_ORANGE_AMPERSAND: equ $A6
VDPTILE_ORANGE_APOSTROPHE: equ $A7
VDPTILE_ORANGE_OPENING_ROUND_BRACKET: equ $A8
VDPTILE_ORANGE_CLOSING_ROUND_BRACKET: equ $A9
VDPTILE_ORANGE_MULTIPLICATION_SIGN: equ $AA
VDPTILE_ORANGE_PLUS_SIGN: equ $AB
VDPTILE_ORANGE_COMMA: equ $AC
VDPTILE_ORANGE_MINUS_SIGN: equ $AD
VDPTILE_ORANGE_DOT: equ $AE
VDPTILE_ORANGE_SLASH: equ $AF
VDPTILE_SWORD_ICON: equ $B0 ; denotes active member
VDPTILE_EQUIPPED_SYMBOL: equ $B1
VDPTILE_ORANGE_NUMBER_0: equ $B2
VDPTILE_ORANGE_NUMBER_1: equ $B3
VDPTILE_ORANGE_NUMBER_2: equ $B4
VDPTILE_ORANGE_NUMBER_3: equ $B5
VDPTILE_ORANGE_NUMBER_4: equ $B6
VDPTILE_ORANGE_NUMBER_5: equ $B7
VDPTILE_ORANGE_NUMBER_6: equ $B8
VDPTILE_ORANGE_NUMBER_7: equ $B9
VDPTILE_ORANGE_NUMBER_8: equ $BA
VDPTILE_ORANGE_NUMBER_9: equ $BB
VDPTILE_ORANGE_COLON: equ $BC
VDPTILE_ORANGE_SEMICOLON: equ $BD
VDPTILE_ORANGE_LESS_THAN_SIGN: equ $BE
VDPTILE_ORANGE_EQUALS_SIGN: equ $BF
VDPTILE_ORANGE_GREATER_THAN_SIGN: equ $C0
VDPTILE_ORANGE_QUESTION_MARK: equ $C1
VDPTILE_ORANGE_AT_SIGN: equ $C2
VDPTILE_ORANGE_UPPERCASE_A: equ $C3
VDPTILE_ORANGE_UPPERCASE_B: equ $C4
VDPTILE_ORANGE_UPPERCASE_C: equ $C5
VDPTILE_ORANGE_UPPERCASE_D: equ $C6
VDPTILE_ORANGE_UPPERCASE_E: equ $C7
VDPTILE_ORANGE_UPPERCASE_F: equ $C8
VDPTILE_ORANGE_UPPERCASE_G: equ $C9
VDPTILE_ORANGE_UPPERCASE_H: equ $CA
VDPTILE_ORANGE_UPPERCASE_I: equ $CB
VDPTILE_ORANGE_UPPERCASE_J: equ $CC
VDPTILE_ORANGE_UPPERCASE_K: equ $CD
VDPTILE_ORANGE_UPPERCASE_L: equ $CE
VDPTILE_ORANGE_UPPERCASE_M: equ $CF
VDPTILE_ORANGE_UPPERCASE_N: equ $D0
VDPTILE_ORANGE_UPPERCASE_O: equ $D1
VDPTILE_ORANGE_UPPERCASE_P: equ $D2
VDPTILE_ORANGE_UPPERCASE_Q: equ $D3
VDPTILE_ORANGE_UPPERCASE_R: equ $D4
VDPTILE_ORANGE_UPPERCASE_S: equ $D5
VDPTILE_ORANGE_UPPERCASE_T: equ $D6
VDPTILE_ORANGE_UPPERCASE_U: equ $D7
VDPTILE_ORANGE_UPPERCASE_V: equ $D8
VDPTILE_ORANGE_UPPERCASE_W: equ $D9
VDPTILE_ORANGE_UPPERCASE_X: equ $DA
VDPTILE_ORANGE_UPPERCASE_Y: equ $DB
VDPTILE_ORANGE_UPPERCASE_Z: equ $DC
VDPTILE_STATUSEFFECT_SLOW1: equ $DD ; left half of icon
VDPTILE_ORANGE_BACKSLASH: equ $DE
VDPTILE_STATUSEFFECT_SLOW2: equ $DF ; right half of icon
VDPTILE_MAX_SYMBOL1: equ $E0 ; left half of icon
VDPTILE_MAX_SYMBOL2: equ $E1 ; right half of icon
VDPTILE_STATUSEFFECT_MUDDLE1: equ $E2 ; left half of icon
VDPTILE_STATUSEFFECT_MUDDLE2: equ $E3 ; right half of icon
VDPTILE_STATUSEFFECT_SILENCE1: equ $E4 ; left half of icon
VDPTILE_STATUSEFFECT_SILENCE2: equ $E5 ; right half of icon
VDPTILE_STATUSEFFECT_SLEEP1: equ $E6 ; left half of icon
VDPTILE_STATUSEFFECT_SLEEP2: equ $E7 ; right half of icon
VDPTILE_STATUSEFFECT_POISON1: equ $E8 ; left half of icon
VDPTILE_STATUSEFFECT_POISON2: equ $E9 ; right half of icon
VDPTILE_STATUSEFFECT_STUN1: equ $EA ; left half of icon
VDPTILE_STATUSEFFECT_STUN2: equ $EB ; right half of icon
VDPTILE_STATUSEFFECT_CURSE1: equ $EC ; left half of icon
VDPTILE_STATUSEFFECT_CURSE2: equ $ED ; right half of icon
VDPTILE_JEWEL_OF_EVIL: equ $EE
VDPTILE_JEWEL_OF_LIGHT: equ $EF
VDPTILE_SPELL_LEVEL1: equ $F0 ; for 1st pip start
VDPTILE_SPELL_LEVEL2: equ $F1 ; for filled end pip
VDPTILE_SPELL_LEVEL3: equ $F2 ; for filled-to-filled pip
VDPTILE_SPELL_LEVEL4: equ $F3 ; 
VDPTILE_SPELL_LEVEL5: equ $F4 ; 
VDPTILE_SPELL_LEVEL6: equ $F5 ; for filled-to-empty pip
VDPTILE_SPELL_LEVEL7: equ $F6 ; for empty-to-empty pip
VDPTILE_SPELL_LEVEL8: equ $F7 ; for empty end pip
VDPTILE_BLANK: equ $F8
VDPTILE_PORTRAITCORNER: equ $F9
VDPTILE_H_PORTRAITBORDER: equ $FA
VDPTILE_V_PORTRAITBORDER: equ $FB
VDPTILE_SHOP_PRICE_TAG_STRING: equ $FC
VDPTILE_RED_DOT: equ $FD ; for enemy designation on minimap
VDPTILE_GREEN_DOT: equ $FE ; for ally designation on minimap
VDPTILE_255: equ $FF

; ---------------------------------------------------------------------------

; enum VdpTiles_MapAndMenu (bitfield)

VDPTILE_MAP_START: equ $100
VDPTILE_ENTITIES_FRAME_1_START: equ $380
VDPTILE_ENTITIES_FRAME_2_START: equ $389

VDPTILE_MENUTILE1: equ $5C0
VDPTILE_MENUTILE2: equ $5C1
VDPTILE_MENUTILE3: equ $5C2
VDPTILE_MENUTILE4: equ $5C3
VDPTILE_MENUTILE5: equ $5C4
VDPTILE_MENUTILE6: equ $5C5
VDPTILE_MENUTILE7: equ $5C6
VDPTILE_MENUTILE8: equ $5C7
VDPTILE_MENUTILE9: equ $5C8
VDPTILE_MENUTILE10: equ $5C9
VDPTILE_MENUTILE11: equ $5CA
VDPTILE_MENUTILE12: equ $5CB
VDPTILE_MENUTILE13: equ $5CC
VDPTILE_MENUTILE14: equ $5CD
VDPTILE_MENUTILE15: equ $5CE
VDPTILE_MENUTILE16: equ $5CF
VDPTILE_MENUTILE17: equ $5D0
VDPTILE_MENUTILE18: equ $5D1
VDPTILE_MENUTILE19: equ $5D2
VDPTILE_MENUTILE20: equ $5D3
VDPTILE_MENUTILE21: equ $5D4
VDPTILE_MENUTILE22: equ $5D5
VDPTILE_MENUTILE23: equ $5D6
VDPTILE_MENUTILE24: equ $5D7
VDPTILE_MENUTILE25: equ $5D8
VDPTILE_MENUTILE26: equ $5D9
VDPTILE_MENUTILE27: equ $5DA
VDPTILE_MENUTILE28: equ $5DB
VDPTILE_MENUTILE29: equ $5DC
VDPTILE_MENUTILE30: equ $5DD
VDPTILE_MENUTILE31: equ $5DE
VDPTILE_MENUTILE32: equ $5DF
VDPTILE_MENUTILE33: equ $5E0
VDPTILE_MENUTILE34: equ $5E1
VDPTILE_MENUTILE35: equ $5E2
VDPTILE_MENUTILE36: equ $5E3
VDPTILE_MENUTILE37: equ $5E4
VDPTILE_MENUTILE38: equ $5E5
VDPTILE_MENUTILE39: equ $5E6
VDPTILE_MENUTILE40: equ $5E7
VDPTILE_MENUTILE41: equ $5E8
VDPTILE_MENUTILE42: equ $5E9
VDPTILE_MENUTILE43: equ $5EA
VDPTILE_MENUTILE44: equ $5EB
VDPTILE_MENUTILE45: equ $5EC
VDPTILE_MENUTILE46: equ $5ED
VDPTILE_MENUTILE47: equ $5EE
VDPTILE_MENUTILE48: equ $5EF
VDPTILE_MENUTILE49: equ $5F0
VDPTILE_MENUTILE50: equ $5F1
VDPTILE_MENUTILE51: equ $5F2
VDPTILE_MENUTILE52: equ $5F3
VDPTILE_MENUTILE53: equ $5F4
VDPTILE_MENUTILE54: equ $5F5
VDPTILE_MENUTILE55: equ $5F6
VDPTILE_MENUTILE56: equ $5F7
VDPTILE_MENUTILE57: equ $5F8
VDPTILE_MENUTILE58: equ $5F9
VDPTILE_MENUTILE59: equ $5FA
VDPTILE_MENUTILE60: equ $5FB
VDPTILE_MENUTILE61: equ $5FC
VDPTILE_MENUTILE62: equ $5FD
VDPTILE_MENUTILE63: equ $5FE
VDPTILE_MENUTILE64: equ $5FF
VDPTILE_MESSAGE_START: equ $640 ; gets written to in VRAM with the VW font when message is being parsed and printed
VDPTILE_ICONS_START: equ $6D0
VDPTILE_SCREEN_BLACK_BAR: equ $77C ; used to hide leftmost column of the screen
VDPTILE_PORTRAITTILE1: equ $7C0
VDPTILE_PORTRAITTILE2: equ $7C1
VDPTILE_PORTRAITTILE3: equ $7C2
VDPTILE_PORTRAITTILE4: equ $7C3
VDPTILE_PORTRAITTILE5: equ $7C4
VDPTILE_PORTRAITTILE6: equ $7C5
VDPTILE_PORTRAITTILE7: equ $7C6
VDPTILE_PORTRAITTILE8: equ $7C7
VDPTILE_PORTRAITTILE9: equ $7C8
VDPTILE_PORTRAITTILE10: equ $7C9
VDPTILE_PORTRAITTILE11: equ $7CA
VDPTILE_PORTRAITTILE12: equ $7CB
VDPTILE_PORTRAITTILE13: equ $7CC
VDPTILE_PORTRAITTILE14: equ $7CD
VDPTILE_PORTRAITTILE15: equ $7CE
VDPTILE_PORTRAITTILE16: equ $7CF
VDPTILE_PORTRAITTILE17: equ $7D0
VDPTILE_PORTRAITTILE18: equ $7D1
VDPTILE_PORTRAITTILE19: equ $7D2
VDPTILE_PORTRAITTILE20: equ $7D3
VDPTILE_PORTRAITTILE21: equ $7D4
VDPTILE_PORTRAITTILE22: equ $7D5
VDPTILE_PORTRAITTILE23: equ $7D6
VDPTILE_PORTRAITTILE24: equ $7D7
VDPTILE_PORTRAITTILE25: equ $7D8
VDPTILE_PORTRAITTILE26: equ $7D9
VDPTILE_PORTRAITTILE27: equ $7DA
VDPTILE_PORTRAITTILE28: equ $7DB
VDPTILE_PORTRAITTILE29: equ $7DC
VDPTILE_PORTRAITTILE30: equ $7DD
VDPTILE_PORTRAITTILE31: equ $7DE
VDPTILE_PORTRAITTILE32: equ $7DF
VDPTILE_PORTRAITTILE33: equ $7E0
VDPTILE_PORTRAITTILE34: equ $7E1
VDPTILE_PORTRAITTILE35: equ $7E2
VDPTILE_PORTRAITTILE36: equ $7E3
VDPTILE_PORTRAITTILE37: equ $7E4
VDPTILE_PORTRAITTILE38: equ $7E5
VDPTILE_PORTRAITTILE39: equ $7E6
VDPTILE_PORTRAITTILE40: equ $7E7
VDPTILE_PORTRAITTILE41: equ $7E8
VDPTILE_PORTRAITTILE42: equ $7E9
VDPTILE_PORTRAITTILE43: equ $7EA
VDPTILE_PORTRAITTILE44: equ $7EB
VDPTILE_PORTRAITTILE45: equ $7EC
VDPTILE_PORTRAITTILE46: equ $7ED
VDPTILE_PORTRAITTILE47: equ $7EE
VDPTILE_PORTRAITTILE48: equ $7EF
VDPTILE_PORTRAITTILE49: equ $7F0
VDPTILE_PORTRAITTILE50: equ $7F1
VDPTILE_PORTRAITTILE51: equ $7F2
VDPTILE_PORTRAITTILE52: equ $7F3
VDPTILE_PORTRAITTILE53: equ $7F4
VDPTILE_PORTRAITTILE54: equ $7F5
VDPTILE_PORTRAITTILE55: equ $7F6
VDPTILE_PORTRAITTILE56: equ $7F7
VDPTILE_PORTRAITTILE57: equ $7F8
VDPTILE_PORTRAITTILE58: equ $7F9
VDPTILE_PORTRAITTILE59: equ $7FA
VDPTILE_PORTRAITTILE60: equ $7FB
VDPTILE_PORTRAITTILE61: equ $7FC
VDPTILE_PORTRAITTILE62: equ $7FD
VDPTILE_PORTRAITTILE63: equ $7FE
VDPTILE_PORTRAITTILE64: equ $7FF

; ---------------------------------------------------------------------------

; enum VdpTiles_Battlescene (bitfield)
VDPTILE_ALLYBATTLESPRITE1: equ $100
VDPTILE_ALLYBATTLESPRITE17: equ $110
VDPTILE_ALLYBATTLESPRITE33: equ $120
VDPTILE_ALLYBATTLESPRITE49: equ $130
VDPTILE_ALLYBATTLESPRITE65: equ $140
VDPTILE_ALLYBATTLESPRITE81: equ $150
VDPTILE_ALLYBATTLESPRITE97: equ $160
VDPTILE_ALLYBATTLESPRITE113: equ $170
VDPTILE_ALLYBATTLESPRITE129: equ $180

VDPTILE_SPELLTILE1: equ $520
VDPTILE_SPELLTILE2: equ $521
VDPTILE_SPELLTILE4: equ $523
VDPTILE_SPELLTILE5: equ $524
VDPTILE_SPELLTILE6: equ $525
VDPTILE_SPELLTILE8: equ $527
VDPTILE_SPELLTILE9: equ $528
VDPTILE_SPELLTILE10: equ $529
VDPTILE_SPELLTILE13: equ $52C
VDPTILE_SPELLTILE14: equ $52D
VDPTILE_SPELLTILE17: equ $530
VDPTILE_SPELLTILE18: equ $531
VDPTILE_SPELLTILE19: equ $532
VDPTILE_SPELLTILE25: equ $538
VDPTILE_SPELLTILE27: equ $53A
VDPTILE_SPELLTILE28: equ $53B
VDPTILE_SPELLTILE29: equ $53C
VDPTILE_SPELLTILE31: equ $53E
VDPTILE_SPELLTILE33: equ $540
VDPTILE_SPELLTILE34: equ $541
VDPTILE_SPELLTILE35: equ $542
VDPTILE_SPELLTILE41: equ $548
VDPTILE_SPELLTILE44: equ $54B
VDPTILE_SPELLTILE50: equ $551
VDPTILE_SPELLTILE51: equ $552
VDPTILE_SPELLTILE57: equ $558
VDPTILE_SPELLTILE60: equ $55B
VDPTILE_SPELLTILE62: equ $55D
VDPTILE_SPELLTILE63: equ $55E
VDPTILE_SPELLTILE65: equ $560
VDPTILE_SPELLTILE66: equ $561
VDPTILE_SPELLTILE68: equ $563
VDPTILE_SPELLTILE70: equ $565
VDPTILE_SPELLTILE73: equ $568
VDPTILE_SPELLTILE77: equ $56C
VDPTILE_SPELLTILE81: equ $570
VDPTILE_SPELLTILE84: equ $573
VDPTILE_SPELLTILE86: equ $575
VDPTILE_SPELLTILE97: equ $580
VDPTILE_SPELLTILE100: equ $583
VDPTILE_SPELLTILE101: equ $584
VDPTILE_SPELLTILE102: equ $585
VDPTILE_SPELLTILE112: equ $58F
VDPTILE_SPELLTILE115: equ $592
VDPTILE_SPELLTILE117: equ $594
VDPTILE_SPELLTILE133: equ $5A4
VDPTILE_SPELLTILE140: equ $5AB
VDPTILE_SPELLTILE145: equ $5B0
VDPTILE_SPELLTILE148: equ $5B3
VDPTILE_SPELLTILE164: equ $5C3

VDPTILE_WEAPON1: equ $6C0
VDPTILE_WEAPON17: equ $6D0
VDPTILE_WEAPON33: equ $6E0
VDPTILE_WEAPON49: equ $6F0

VDPTILE_GROUND1: equ $780
VDPTILE_GROUND17: equ $790
VDPTILE_GROUND33: equ $7A0

VDPTILE_TILE1503: equ $5DF
VDPTILE_TILE1920: equ $780
VDPTILE_TILE1924: equ $784

; ---------------------------------------------------------------------------

; enum VdpTile_Masks
VDPTILE_INDEX_MASK: equ $7FF
VDPTILE_PALETTES_MASK: equ $6000
VDPTILE_PROPERTIES_MASK: equ $F800

; ---------------------------------------------------------------------------

; enum VdpTile properties (bitfield)
VDPTILE_MIRROR_BYTE: equ $8
VDPTILE_FLIP_BYTE: equ $10

VDPTILE_MIRROR: equ $800
VDPTILE_FLIP: equ $1000
VDPTILE_PALETTE1: equ 0
VDPTILE_PALETTE2: equ $2000
VDPTILE_PALETTE3: equ $4000
VDPTILE_PALETTE4: equ $6000
VDPTILE_PRIORITY: equ $8000

; ---------------------------------------------------------------------------

; enum VdpTiles_StatusEffects
VDPTILES_STATUSEFFECT_ATTACK: equ $C0A1C0A2 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_BOOST: equ $C0A3C0A4 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_SLOW: equ $C0DDC0DF ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_MUDDLE: equ $C0E2C0E3 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_SILENCE: equ $C0E4C0E5 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_SLEEP: equ $C0E6C0E7 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_POISON: equ $C0E8C0E9 ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_STUN: equ $C0EAC0EB ; total icon in palette 3 with priority
VDPTILES_STATUSEFFECT_CURSE: equ $C0ECC0ED ; total icon in palette 3 with priority

; ---------------------------------------------------------------------------

; enum VdpSprite_Offsets
VDPSPRITE_OFFSET_Y: equ 0
VDPSPRITE_OFFSET_SIZE: equ 2
VDPSPRITE_OFFSET_LINK: equ 3
VDPSPRITE_OFFSET_TILE: equ 4
VDPSPRITE_OFFSET_X: equ 6
NEXTVDPSPRITE_OFFSET_Y: equ 8
NEXTVDPSPRITE_OFFSET_SIZE: equ 10
NEXTVDPSPRITE_OFFSET_LINK: equ 11
NEXTVDPSPRITE_OFFSET_TILE: equ 12
NEXTVDPSPRITE_OFFSET_X: equ 14

; ---------------------------------------------------------------------------

; enum VdpSprite_Properties
VDP_SPRITE_SHIFT_COUNT: equ 3
VDP_SPRITE_ENTRY_SIZE: equ 8
VDP_SPRITES_COUNTER: equ 63

; ---------------------------------------------------------------------------

; enum VdpSpriteSize (bitfield)
VDPSPRITESIZE_V1: equ 0 ; vertical tile size
VDPSPRITESIZE_V2: equ $100
VDPSPRITESIZE_V3: equ $200
VDPSPRITESIZE_V4: equ $300
VDPSPRITESIZE_H1: equ 0 ; horizontal tile size
VDPSPRITESIZE_H2: equ $400
VDPSPRITESIZE_H3: equ $800
VDPSPRITESIZE_H4: equ $C00

; ---------------------------------------------------------------------------

; enum VdpSpell_Offsets
VDPSPELL_OFFSET_X: equ $0
VDPSPELL_OFFSET_Y: equ $2
VDPSPELL_OFFSET_GRAPHIC: equ $4
VDPSPELL_OFFSET_SIZE: equ $6
VDPSPELL_OFFSET_LINK: equ $7

; ---------------------------------------------------------------------------

; enum VdpGraphicDimension (bitfield)
VDPGRAPHICDIMENSION_V1: equ 0 ; graphic height in tiles
VDPGRAPHICDIMENSION_V2: equ $100
VDPGRAPHICDIMENSION_V3: equ $200
VDPGRAPHICDIMENSION_V4: equ $300
VDPGRAPHICDIMENSION_H1: equ 0 ; graphic width in tiles
VDPGRAPHICDIMENSION_H2: equ $400
VDPGRAPHICDIMENSION_H3: equ $800
VDPGRAPHICDIMENSION_H4: equ $C00

; ---------------------------------------------------------------------------

; enum VdpGraphicVolume
GRAPHIC_APOLLO_CLOUD1: equ 4
GRAPHIC_APOLLO_CLOUD2: equ 4
GRAPHIC_APOLLO_ORB1: equ 4
GRAPHIC_APOLLO_ORB2: equ 4
GRAPHIC_APOLLO_ORB3: equ 4
GRAPHIC_APOLLO_ORB4: equ 4
GRAPHIC_APOLLO_EXPLOSION1: equ 16
GRAPHIC_APOLLO_EXPLOSION2: equ 16
GRAPHIC_APOLLO_EXPLOSION3: equ 16
GRAPHIC_APOLLO_EXPLOSION4: equ 16

GRAPHIC_ARROWSPEAR_ARROW1: equ 4
GRAPHIC_ARROWSPEAR_ARROW2: equ 5
GRAPHIC_ARROWSPEAR_SPEAR: equ 8

GRAPHIC_BEAM_ORB: equ 4
GRAPHIC_BEAM_BEAM: equ 12

GRAPHIC_BLAST_SLASH_ORANGE1: equ 1
GRAPHIC_BLAST_SLASH_ORANGE2: equ 4
GRAPHIC_BLAST_SLASH_ORANGE3: equ 6
GRAPHIC_BLAST_SLASH_ORANGE4: equ 12
GRAPHIC_BLAST_SLASH_ORANGE5: equ 2
GRAPHIC_BLAST_SLASH_ORANGE6: equ 4
GRAPHIC_BLAST_SLASH_ORANGE7: equ 6
GRAPHIC_BLAST_SLASH_ORANGE8: equ 8
GRAPHIC_BLAST_CYCLONE1: equ 32
GRAPHIC_BLAST_CYCLONE2: equ 32
GRAPHIC_BLAST_CYCLONE3: equ 32
GRAPHIC_BLAST_EXPLOSION1: equ 4
GRAPHIC_BLAST_EXPLOSION2: equ 4
GRAPHIC_BLAST_EXPLOSION3: equ 4
GRAPHIC_BLAST_SLASH_BLUE1: equ 4
GRAPHIC_BLAST_SLASH_BLUE2: equ 8
GRAPHIC_BLAST_SLASH_BLUE3: equ 6
GRAPHIC_BLAST_SLASH_BLUE4: equ 2
GRAPHIC_BLAST_SLASH_BLUE5: equ 8
GRAPHIC_BLAST_SLASH_BLUE6: equ 6
GRAPHIC_BLAST_SLASH_BLUE7: equ 4
GRAPHIC_BLAST_SLASH_BLUE8: equ 16
GRAPHIC_BLAST_SLASH_BLUE9: equ 6

GRAPHIC_BLAZE_DRAGON1: equ 4
GRAPHIC_BLAZE_DRAGON2: equ 4
GRAPHIC_BLAZE_DRAGON3: equ 9
GRAPHIC_BLAZE_DRAGON4: equ 16
GRAPHIC_BLAZE_FLAME1: equ 8
GRAPHIC_BLAZE_FLAME2: equ 8
GRAPHIC_BLAZE_FLAME3: equ 18
GRAPHIC_BLAZE_FLAME4: equ 18
GRAPHIC_BLAZE_FLAME5: equ 32
GRAPHIC_BLAZE_FLAME6: equ 32
GRAPHIC_BLAZE_METEOR1: equ 4
GRAPHIC_BLAZE_METEOR2: equ 4
GRAPHIC_BLAZE_EXPLOSION1: equ 9
GRAPHIC_BLAZE_EXPLOSION2: equ 6
GRAPHIC_BLAZE_METEOR3: equ 9
GRAPHIC_BLAZE_METEOR4: equ 9
GRAPHIC_BLAZE_EXPLOSION3: equ 16
GRAPHIC_BLAZE_EXPLOSION4: equ 16

GRAPHIC_BOLT_1: equ 4
GRAPHIC_BOLT_2: equ 4
GRAPHIC_BOLT_3: equ 4
GRAPHIC_BOLT_4: equ 4
GRAPHIC_BOLT_STRIKE1: equ 49
GRAPHIC_BOLT_STRIKE2: equ 49
GRAPHIC_BOLT_STRIKE3: equ 33
GRAPHIC_BOLT_ORB1: equ 16
GRAPHIC_BOLT_ORB2: equ 16

GRAPHIC_BUBBLEBREATH_BUBBLE1: equ 1
GRAPHIC_BUBBLEBREATH_BUBBLE2: equ 1
GRAPHIC_BUBBLEBREATH_BUBBLE3: equ 1
GRAPHIC_BUBBLEBREATH_BUBBLE4: equ 1
GRAPHIC_BUBBLEBREATH_BUBBLE5: equ 4
GRAPHIC_BUBBLEBREATH_BUBBLE6: equ 9
GRAPHIC_BUBBLEBREATH_BUBBLE7: equ 16

GRAPHIC_BURST_EXPLOSION1: equ 16
GRAPHIC_BURST_EXPLOSION2: equ 16
GRAPHIC_BURST_EXPLOSION3: equ 16
GRAPHIC_BURST_EXPLOSION4: equ 16
GRAPHIC_BURST_EXPLOSION5: equ 4
GRAPHIC_BURST_EXPLOSION6: equ 4
GRAPHIC_BURST_EXPLOSION7: equ 4
GRAPHIC_BURST_SHOT1: equ 4
GRAPHIC_BURST_SHOT2: equ 4

GRAPHIC_CANNON_SHOT1: equ 4
GRAPHIC_CANNON_SHOT2: equ 4

GRAPHIC_DAO_STONE_SMALL: equ 1
GRAPHIC_DAO_STONE_MEDIUM: equ 6
GRAPHIC_DAO_STONE_LARGE: equ 12

GRAPHIC_DEBUFF_CLOUD1: equ 16
GRAPHIC_DEBUFF_CLOUD2: equ 16
GRAPHIC_DEBUFF_CLOUD3: equ 16

GRAPHIC_DESOUL_REAPER1: equ 48
GRAPHIC_DESOUL_REAPER2: equ 48
GRAPHIC_DESOUL_SOUL1: equ 4
GRAPHIC_DESOUL_SOUL2: equ 4

GRAPHIC_DODGE_DUST1: equ 4
GRAPHIC_DODGE_DUST2: equ 4
GRAPHIC_DODGE_DUST3: equ 4

GRAPHIC_DEMONBREATH_HEAD1: equ 16
GRAPHIC_DEMONBREATH_HEAD2: equ 16
GRAPHIC_DEMONBREATH_HEAD3: equ 16
GRAPHIC_DEMONBREATH_HEAD4: equ 16
GRAPHIC_DEMONBREATH_HEAD5: equ 16
GRAPHIC_DEMONBREATH_HEAD6: equ 16

GRAPHIC_DETOX_WHITE_LARGE1: equ 9
GRAPHIC_DETOX_WHITE_LARGE2: equ 9
GRAPHIC_DETOX_WHITE_MEDIUM1: equ 4
GRAPHIC_DETOX_WHITE_MEDIUM2: equ 4
GRAPHIC_DETOX_WHITE_SMALL1: equ 1
GRAPHIC_DETOX_WHITE_SMALL2: equ 1
GRAPHIC_DETOX_WHITE_GOLD1: equ 1
GRAPHIC_DETOX_WHITE_GOLD2: equ 1
GRAPHIC_DETOX_WHITE_GOLD3: equ 1
GRAPHIC_DETOX_WHITE_GOLD4: equ 1

GRAPHIC_FLAMEBREATH_FLAME1: equ 1
GRAPHIC_FLAMEBREATH_FLAME2: equ 1
GRAPHIC_FLAMEBREATH_FLAME3: equ 4
GRAPHIC_FLAMEBREATH_FLAME4: equ 4
GRAPHIC_FLAMEBREATH_FLAME5: equ 9
GRAPHIC_FLAMEBREATH_FLAME6: equ 16

GRAPHIC_FREEZE_FLAKE1: equ 1
GRAPHIC_FREEZE_FLAKE2: equ 1
GRAPHIC_FREEZE_FLAKE3: equ 4
GRAPHIC_FREEZE_FLAKE4: equ 9
GRAPHIC_FREEZE_FLAKE5: equ 9
GRAPHIC_FREEZE_FLAKE6: equ 16
GRAPHIC_FREEZE_STONE1: equ 1
GRAPHIC_FREEZE_STONE2: equ 1
GRAPHIC_FREEZE_STONE3: equ 4
GRAPHIC_FREEZE_STONE4: equ 9
GRAPHIC_FREEZE_STONE5: equ 9
GRAPHIC_FREEZE_STONE6: equ 16
GRAPHIC_FREEZE_DIAMOND1: equ 3
GRAPHIC_FREEZE_DIAMOND2: equ 3

GRAPHIC_FROSTBREATH_SWIRL_SMALL1: equ 4
GRAPHIC_FROSTBREATH_SWIRL_SMALL2: equ 4
GRAPHIC_FROSTBREATH_SWIRL_SMALL3: equ 4
GRAPHIC_FROSTBREATH_SWIRL_SMALL4: equ 4
GRAPHIC_FROSTBREATH_SWIRL_SMALL5: equ 4
GRAPHIC_FROSTBREATH_SWIRL_SMALL6: equ 4
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM1: equ 9
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM2: equ 9
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM3: equ 9
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM4: equ 9
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM5: equ 9
GRAPHIC_FROSTBREATH_SWIRL_MEDIUM6: equ 9
GRAPHIC_FROSTBREATH_SWIRL_LARGE1: equ 16
GRAPHIC_FROSTBREATH_SWIRL_LARGE2: equ 16
GRAPHIC_FROSTBREATH_SWIRL_LARGE3: equ 16
GRAPHIC_FROSTBREATH_SWIRL_LARGE4: equ 16
GRAPHIC_FROSTBREATH_SWIRL_LARGE5: equ 16
GRAPHIC_FROSTBREATH_SWIRL_LARGE6: equ 16

GRAPHIC_GUNNER_TWINKLE1: equ 4
GRAPHIC_GUNNER_TWINKLE2: equ 4
GRAPHIC_GUNNER_BLAST1: equ 72
GRAPHIC_GUNNER_BLAST2: equ 72
GRAPHIC_GUNNER_BLAST3: equ 72

GRAPHIC_HEALING_FAIRY1: equ 16
GRAPHIC_HEALING_FAIRY2: equ 16
GRAPHIC_HEALING_WINGS1: equ 4
GRAPHIC_HEALING_WINGS2: equ 4
GRAPHIC_HEALING_WINGS3: equ 4
GRAPHIC_HEALING_WINGS4: equ 4
GRAPHIC_HEALING_TWINKLE1: equ 1
GRAPHIC_HEALING_TWINKLE2: equ 1
GRAPHIC_HEALING_TWINKLE3: equ 1
GRAPHIC_HEALING_TWINKLE4: equ 1
GRAPHIC_HEALING_TWINKLE5: equ 1
GRAPHIC_HEALING_FAIRY3: equ 16
GRAPHIC_HEALING_FAIRY4: equ 16
GRAPHIC_HEALING_WINGS5: equ 4
GRAPHIC_HEALING_WINGS6: equ 4
GRAPHIC_HEALING_WINGS7: equ 4
GRAPHIC_HEALING_WINGS8: equ 4
GRAPHIC_HEALING_TWINKLE6: equ 1
GRAPHIC_HEALING_TWINKLE7: equ 1
GRAPHIC_HEALING_TWINKLE8: equ 1
GRAPHIC_HEALING_TWINKLE9: equ 1
GRAPHIC_HEALING_TWINKLE10: equ 1

GRAPHIC_NEPTUN_SPHERE1: equ 6
GRAPHIC_NEPTUN_SPHERE2: equ 6
GRAPHIC_NEPTUN_SPHERE3: equ 6
GRAPHIC_NEPTUN_RAINSTREAK: equ 12
GRAPHIC_NEPTUN_SIZZLE1: equ 4
GRAPHIC_NEPTUN_SIZZLE2: equ 4
GRAPHIC_NEPTUN_SIZZLE3: equ 4

GRAPHIC_PRISMLASER_TWINKLE1: equ 1
GRAPHIC_PRISMLASER_TWINKLE2: equ 1
GRAPHIC_PRISMLASER_TWINKLE3: equ 1
GRAPHIC_PRISMLASER_SPHERE1: equ 16
GRAPHIC_PRISMLASER_SPHERE2: equ 16
GRAPHIC_PRISMLASER_SPHERE3: equ 16
GRAPHIC_PRISMLASER_SPHERE4: equ 16
GRAPHIC_PRISMLASER_BEAM1: equ 16
GRAPHIC_PRISMLASER_BEAM2: equ 16
GRAPHIC_PRISMLASER_BEAM3: equ 16

GRAPHIC_SOUND_WAVE1: equ 16
GRAPHIC_SOUND_WAVE2: equ 16
GRAPHIC_SOUND_WAVE3: equ 16
GRAPHIC_SOUND_WAVE4: equ 16

