
; SCRIPT SECTION mapsetups\map34\s1 :
; 
ms_map34_Entities:  dc.b 7
										dc.b $A
										dc.b 1
										dc.b $D4
										dc.l eas_Init           
										dc.b 6
										dc.b $A
										dc.b 1
										dc.b $DB
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $FC
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $DE
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $C8
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $3F
										dc.l eas_Init3          
