
; SCRIPT SECTION maps\entries\map38\mapsetups\s1 :
; 
ms_map38_Entities:  dc.b $C
										dc.b $1B
										dc.b 0
										dc.b $C4
										dc.l eas_Init           
										dc.b $16
										dc.b $14
										dc.b 3
										dc.b $C3
										dc.b $FF
										dc.b $16
										dc.b $14
										dc.b 1
										dc.b 8
										dc.b $13
										dc.b 3
										dc.b $C5
										dc.b $FF
										dc.b 8
										dc.b $13
										dc.b 1
										dc.b $B
										dc.b $B
										dc.b 3
										dc.b $C2
										dc.b $FF
										dc.b $B
										dc.b $B
										dc.b 1
										dc.b $16
										dc.b $A
										dc.b 3
										dc.b $C4
										dc.l eas_Init           
										dc.b $1E
										dc.b 5
										dc.b 0
										dc.b $CA
										dc.l eas_Init           
										dc.b $15
										dc.b 3
										dc.b 3
										dc.b $C2
										dc.b $FF
										dc.b $15
										dc.b 3
										dc.b 1
										dc.b 5
										dc.b $A
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b 5
										dc.b $A
										dc.b 1
										dc.b 3
										dc.b $10
										dc.b 0
										dc.b $CA
										dc.l eas_Init           
										dc.b $C
										dc.b 3
										dc.b 0
										dc.b $C4
										dc.l eas_Init           
										dc.b $D
										dc.b 4
										dc.b 1
										dc.b $C5
										dc.l eas_Init           
										dc.b $16
										dc.b $1B
										dc.b 2
										dc.b $C0
										dc.l eas_Init           
										dc.b $1F
										dc.b $E
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $23
										dc.b 4
										dc.b 2
										dc.b $C1
										dc.l eas_Init           
										dc.b $D
										dc.b 3
										dc.b 3
										dc.b $C2
										dc.l eas_Init3          
										dc.w $FFFF
