
; SCRIPT SECTION mapsetups\map05\s1 :
; 
ms_map5_Entities:   dc.b 7
										dc.b 6
										dc.b 3
										dc.b 4
										dc.l eas_Init           
										dc.b $16
										dc.b $24
										dc.b 3
										dc.b $C6
										dc.b $FF
										dc.b $16
										dc.b $24
										dc.b 1
										dc.b $14
										dc.b $1C
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b $14
										dc.b $1C
										dc.b 1
										dc.b $14
										dc.b $10
										dc.b 0
										dc.b $C6
										dc.l eas_Init           
										dc.b $16
										dc.b $10
										dc.b 2
										dc.b $C3
										dc.l eas_Init           
										dc.b $13
										dc.b $C
										dc.b 3
										dc.b $C2
										dc.l eas_Init           
										dc.b $15
										dc.b $15
										dc.b 3
										dc.b $EB
										dc.b $FF
										dc.b $15
										dc.b $15
										dc.b 2
										dc.b $16
										dc.b $15
										dc.b 3
										dc.b $EB
										dc.b $FF
										dc.b $16
										dc.b $15
										dc.b 2
										dc.b $19
										dc.b $13
										dc.b 3
										dc.b $C8
										dc.l eas_Init           
										dc.b 9
										dc.b $10
										dc.b 3
										dc.b $C6
										dc.l eas_Init           
										dc.b $F
										dc.b $14
										dc.b 2
										dc.b $C3
										dc.l eas_Init           
										dc.b $E
										dc.b $11
										dc.b 3
										dc.b $C4
										dc.l eas_Init           
										dc.b 7
										dc.b $14
										dc.b 3
										dc.b $C5
										dc.b $FF
										dc.b 7
										dc.b $14
										dc.b 1
										dc.b 8
										dc.b 6
										dc.b 3
										dc.b $C5
										dc.l eas_Init           
										dc.b $B
										dc.b 4
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b $B
										dc.b 7
										dc.b 3
										dc.b $D2
										dc.b $FF
										dc.b $B
										dc.b 7
										dc.b 1
										dc.w $FFFF
