
; SCRIPT SECTION mapsetups\map05\s2 :
; 
ms_map5_EntityEvents:
										dc.b 4
										dc.b 3
										dc.w sub_51AC2-ms_map5_EntityEvents
										dc.b $80
										dc.b 1
										dc.w sub_51B1E-ms_map5_EntityEvents
										dc.b $81
										dc.b 1
										dc.w sub_51B24-ms_map5_EntityEvents
										dc.b $82
										dc.b 3
										dc.w sub_51B2E-ms_map5_EntityEvents
										dc.b $83
										dc.b 3
										dc.w sub_51B38-ms_map5_EntityEvents
										dc.b $84
										dc.b 3
										dc.w sub_51B42-ms_map5_EntityEvents
										dc.b $85
										dc.b 1
										dc.w sub_51B50-ms_map5_EntityEvents
										dc.b $86
										dc.b 1
										dc.w sub_51B56-ms_map5_EntityEvents
										dc.b $87
										dc.b 3
										dc.w sub_51B5C-ms_map5_EntityEvents
										dc.b $88
										dc.b 3
										dc.w sub_51B62-ms_map5_EntityEvents
										dc.b $89
										dc.b 3
										dc.w sub_51B6C-ms_map5_EntityEvents
										dc.b $8A
										dc.b 3
										dc.w sub_51B7A-ms_map5_EntityEvents
										dc.b $8B
										dc.b 1
										dc.w sub_51B80-ms_map5_EntityEvents
										dc.b $8C
										dc.b 3
										dc.w sub_51B8E-ms_map5_EntityEvents
										dc.b $8D
										dc.b 3
										dc.w sub_51BAE-ms_map5_EntityEvents
										dc.b $8E
										dc.b 1
										dc.w sub_51BA8-ms_map5_EntityEvents
										dc.w $FD00
										dc.w nullsub_113-ms_map5_EntityEvents
