
; SCRIPT SECTION mapsetups\map36\s1_212 :
; 
ms_map36_flag212_Entities:
										dc.b $1B
										dc.b 8
										dc.b 2
										dc.b $16
										dc.l eas_Init           
										dc.b $19
										dc.b $18
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b $C
										dc.b $19
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $C
										dc.b $19
										dc.b 1
										dc.b $15
										dc.b $10
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $15
										dc.b $10
										dc.b 1
										dc.b 8
										dc.b 3
										dc.b 3
										dc.b $E9
										dc.l eas_Init           
										dc.b 5
										dc.b $16
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b $28
										dc.b $11
										dc.b 3
										dc.b $E9
										dc.l eas_Init           
										dc.b $1D
										dc.b 3
										dc.b 3
										dc.b $E7
										dc.l eas_Init           
										dc.b $1F
										dc.b 5
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b $1F
										dc.b $B
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b $28
										dc.b 4
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.w $FFFF
