
; SCRIPT SECTION maps\entries\map09\mapsetups\s1 :
; 
ms_map9_Entities:   dc.b $10
										dc.b $3B
										dc.b 3
										dc.b $B
										dc.l eas_Init           
										dc.b $D
										dc.b $D
										dc.b 3
										dc.b $E1
										dc.b $FF
										dc.b $D
										dc.b $D
										dc.b 2
										dc.b $14
										dc.b $29
										dc.b 3
										dc.b $C2
										dc.b $FF
										dc.b $14
										dc.b $29
										dc.b 2
										dc.b 7
										dc.b $3A
										dc.b 1
										dc.b $C0
										dc.l eas_Init2          
										dc.b $14
										dc.b 8
										dc.b 3
										dc.b $C1
										dc.b $FF
										dc.b $14
										dc.b 8
										dc.b 1
										dc.b $1A
										dc.b 7
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b 8
										dc.b 7
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b $C
										dc.b $14
										dc.b 0
										dc.b $CD
										dc.l eas_Init           
										dc.b $17
										dc.b $1F
										dc.b 3
										dc.b $C0
										dc.b $FF
										dc.b $17
										dc.b $1F
										dc.b 2
										dc.b $11
										dc.b $1D
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b $11
										dc.b $1D
										dc.b 2
										dc.b $10
										dc.b 3
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.w $FFFF
