
; ASM FILE code\common\tech\graphics\specialspritesanims.asm :
; 0x2784C..0x2791C : Special Sprites Animations
word_2784C:     dc.w $5C
                dc.b $A
                dc.b $3D
                dc.w $6578
                dc.w $74
                dc.w $74
                dc.b $A
                dc.b $3E
                dc.w $6581
                dc.w $74
                dc.w $5C
                dc.b $A
                dc.b $3F
                dc.w $658A
                dc.w $8C
                dc.w $74
                dc.b $A
                dc.b 0
                dc.w $6593
                dc.w $8C
word_2786C:     dc.w $5C
                dc.b $A
                dc.b $3D
                dc.w $659C
                dc.w $74
                dc.w $74
                dc.b $A
                dc.b $3E
                dc.w $65A5
                dc.w $74
                dc.w $5C
                dc.b $A
                dc.b $3F
                dc.w $65AE
                dc.w $8C
                dc.w $74
                dc.b $A
                dc.b 0
                dc.w $65B7
                dc.w $8C
SpecialSpriteData_NazcaShip:
                dc.w $60
                dc.b $A
                dc.b $38
                dc.w $651E
                dc.w $68
                dc.w $78
                dc.b $A
                dc.b $39
                dc.w $6527
                dc.w $68
                dc.w $90
                dc.b $A
                dc.b $3A
                dc.w $6530
                dc.w $68
                dc.w $60
                dc.b $A
                dc.b $3B
                dc.w $6539
                dc.w $80
                dc.w $78
                dc.b $A
                dc.b $3C
                dc.w $6542
                dc.w $80
                dc.w $90
                dc.b $A
                dc.b $3D
                dc.w $654B
                dc.w $80
                dc.w $90
                dc.b $A
                dc.b $3E
                dc.w $6554
                dc.w $98
                dc.w $78
                dc.b $A
                dc.b $3F
                dc.w $655D
                dc.w $98
                dc.w $90
                dc.b $A
                dc.b 0
                dc.w $6566
                dc.w $98
                dc.w $60
                dc.b $A
                dc.b $38
                dc.w $656F
                dc.w $68
                dc.w $78
                dc.b $A
                dc.b $39
                dc.w $6578
                dc.w $68
                dc.w $90
                dc.b $A
                dc.b $3A
                dc.w $6581
                dc.w $68
                dc.w $60
                dc.b $A
                dc.b $3B
                dc.w $658A
                dc.w $80
                dc.w $78
                dc.b $A
                dc.b $3C
                dc.w $6593
                dc.w $80
                dc.w $90
                dc.b $A
                dc.b $3D
                dc.w $659C
                dc.w $80
                dc.w $90
                dc.b $A
                dc.b $3E
                dc.w $65A5
                dc.w $98
                dc.w $78
                dc.b $A
                dc.b $3F
                dc.w $65AE
                dc.w $98
                dc.w $90
                dc.b $A
                dc.b 0
                dc.w $65B7
                dc.w $98
