
; ASM FILE code\common\tech\graphics\specialspritesanims.asm :
; 0x2784C..0x2791C : Special Sprites Animations
byte_2784C:     dc.b 0
                dc.b $5C 
                dc.b  $A
                dc.b $3D 
                dc.b $65 
                dc.b $78 
                dc.b   0
                dc.b $74 
                dc.b   0
                dc.b $74 
                dc.b  $A
                dc.b $3E 
                dc.b $65 
                dc.b $81 
                dc.b   0
                dc.b $74 
                dc.b   0
                dc.b $5C 
                dc.b  $A
                dc.b $3F 
                dc.b $65 
                dc.b $8A 
                dc.b   0
                dc.b $8C 
                dc.b   0
                dc.b $74 
                dc.b  $A
                dc.b   0
                dc.b $65 
                dc.b $93 
                dc.b   0
                dc.b $8C 
byte_2786C:     dc.b 0
                dc.b $5C 
                dc.b  $A
                dc.b $3D 
                dc.b $65 
                dc.b $9C 
                dc.b   0
                dc.b $74 
                dc.b   0
                dc.b $74 
                dc.b  $A
                dc.b $3E 
                dc.b $65 
                dc.b $A5 
                dc.b   0
                dc.b $74 
                dc.b   0
                dc.b $5C 
                dc.b  $A
                dc.b $3F 
                dc.b $65 
                dc.b $AE 
                dc.b   0
                dc.b $8C 
                dc.b   0
                dc.b $74 
                dc.b  $A
                dc.b   0
                dc.b $65 
                dc.b $B7 
                dc.b   0
                dc.b $8C 
SpecialSpriteData_NazcaShip:
                dc.b 0
                dc.b $60 
                dc.b  $A
                dc.b $38 
                dc.b $65 
                dc.b $1E
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $39 
                dc.b $65 
                dc.b $27 
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3A 
                dc.b $65 
                dc.b $30 
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $60 
                dc.b  $A
                dc.b $3B 
                dc.b $65 
                dc.b $39 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $3C 
                dc.b $65 
                dc.b $42 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3D 
                dc.b $65 
                dc.b $4B 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3E 
                dc.b $65 
                dc.b $54 
                dc.b   0
                dc.b $98 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $3F 
                dc.b $65 
                dc.b $5D 
                dc.b   0
                dc.b $98 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b   0
                dc.b $65 
                dc.b $66 
                dc.b   0
                dc.b $98 
                dc.b   0
                dc.b $60 
                dc.b  $A
                dc.b $38 
                dc.b $65 
                dc.b $6F 
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $39 
                dc.b $65 
                dc.b $78 
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3A 
                dc.b $65 
                dc.b $81 
                dc.b   0
                dc.b $68 
                dc.b   0
                dc.b $60 
                dc.b  $A
                dc.b $3B 
                dc.b $65 
                dc.b $8A 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $3C 
                dc.b $65 
                dc.b $93 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3D 
                dc.b $65 
                dc.b $9C 
                dc.b   0
                dc.b $80 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b $3E 
                dc.b $65 
                dc.b $A5 
                dc.b   0
                dc.b $98 
                dc.b   0
                dc.b $78 
                dc.b  $A
                dc.b $3F 
                dc.b $65 
                dc.b $AE 
                dc.b   0
                dc.b $98 
                dc.b   0
                dc.b $90 
                dc.b  $A
                dc.b   0
                dc.b $65 
                dc.b $B7 
                dc.b   0
                dc.b $98 
