

; ---------------------------------------------------------------------------

; enum Animation
ANIM_SPRITE_DEATH_SPIN_DELAY: equ $3
ANIM_SPRITE_DEATH_NUM_SPINS: equ $B

; ---------------------------------------------------------------------------

; enum Traps
SOUND_COMMAND: equ $0
CHECK_FLAG: equ $1
SET_FLAG: equ $2
CLEAR_FLAG: equ $3
TEXTBOX: equ $5
MAPSCRIPT: equ $6
VINT_FUNCTIONS: equ $9

; ---------------------------------------------------------------------------

; enum VintActions
VINTS_CLEAR: equ $0
VINTS_ADD: equ $1
VINTS_REMOVE: equ $2
VINTS_DEACTIVATE: equ $3
VINTS_ACTIVATE: equ $4

; ---------------------------------------------------------------------------

; enum VIntBitmap
VDP_COMMAND_REQUEST: equ $0
DEACTIVATE_DMA: equ $1
DMA_REQUEST: equ $3
VRAM_READ_REQUEST: equ $4
ENABLE_VINT: equ $7

; ---------------------------------------------------------------------------

; enum GraphicsValues
GFX_MAX_SPRITES_TO_LOAD: equ $7
GFX_DIAMENU_ICON_NUM_PIXELS: equ $240

; ---------------------------------------------------------------------------

; enum Combatant
COM_ALLY_START: equ $0
COM_POS_IDX: equ $0
COM_BIT_SORT: equ $6
COM_POS_TYPE: equ $7
COM_ALLIES_COUNTER: equ $1D
COM_ALLY_END: equ $1D
COM_ALLIES_NUM: equ $1E
COM_ENEMIES_COUNTER: equ $1F
COM_ALLY_SPACEEND: equ $1F
COM_ALL_COUNTER: equ $3D
COM_IDX_REALMASK: equ $3F
COM_ALLYENDENEMYSTARTDIFFERENCE: equ $60
COM_TYPE_REALMASK: equ $80
COM_ENEMY_START: equ $80
COM_ENEMY_END: equ $9F
COM_ENEMY_SPACEEND: equ $A0

; ---------------------------------------------------------------------------

; enum Combatant_Idx
COM_IDX_SIZE: equ $6
COM_IDX_MASK: equ $3F

; ---------------------------------------------------------------------------

; enum Combatant_Type
COM_TYPE_MASK: equ $1
COM_TYPE_SIZE: equ $1

; ---------------------------------------------------------------------------

; enum Combatant_Offsets

; ---------------------------------------------------------------------------

; enum Combatant_Status_Bitfield
COM_STATUS_MASK_MUDDLE2: equ $8
COM_STATUS_MASK_MUDDLE: equ $30
COM_STATUS_MASK_SLEEP: equ $C0

; ---------------------------------------------------------------------------

; enum CharDef
CHAR_IDX_BOWIE: equ $0
CHARDEF_STARTDATA_ENTRYSIZE: equ $6
CHAR_IDX_PETER: equ $7
CHAR_CLASS_FIRSTPROMOTED: equ $C
CHAR_CLASS_EXTRALEVEL: equ $14
CHAR_IDX_LEMON: equ $1C
CHAR_MAX_IDX: equ $1D
CHAR_STATCAP_AGI_BASE: equ $64
CHAR_STATCAP_AGI_CURRENT: equ $7F
CHAR_STATCAP_LEVEL: equ $C8
CHAR_STATCAP_HP: equ $C8
CHAR_STATCAP_MP: equ $C8
CHAR_STATCAP_ATK: equ $C8
CHAR_STATCAP_DEF: equ $C8
CHAR_STATCAP_MOV: equ $C8
CHAR_STATCAP_EXP: equ $C8
CHAR_STATCAP_AGI_DECREASING: equ $C8

; ---------------------------------------------------------------------------

; enum ClassIdx
CLASSIDX_SORC: equ $12
CLASSIDX_MMNK: equ $14
CLASSIDX_NINJ: equ $1B

; ---------------------------------------------------------------------------

; enum Force
FORCE_MAX_SIZE: equ $C
FORCE_MAX_GOLD: equ $98967F

; ---------------------------------------------------------------------------

; enum Enemy
ENEMYIDX_BURST_ROCK: equ $20
ENEMYIDX_TAROS: equ $58

; ---------------------------------------------------------------------------

; enum CharEntry
CHAR_STATUS_MASK_STUN: equ $1
CHAR_STATUS_BIT_POISON: equ $1
CHAR_ITEMSLOTS_COUNTER: equ $3
CHAR_SPELLSLOTS_COUNTER: equ $3
CHAR_ITEMSLOTS: equ $4
CHAR_SPELLSLOTS: equ $4
CHAR_STATUS_MASK_CURSE: equ $4
CHAR_BIT_ENEMY: equ $7
CHAR_NAME_COUNTER: equ $9
CHAR_NAMELENGTH: equ $A
CHAR_PROWESS_MASK_CRIT: equ $F
CHAR_ENTRY_SIZE: equ $38
CHAR_STATUS_MASK_SILENCE: equ $300

; ---------------------------------------------------------------------------

; enum CharEntry_Offsets
CHAR_OFFSET_NAME: equ $0
CHAR_OFFSET_CLASS_IDX: equ $A
CHAR_OFFSET_LEVEL: equ $B
CHAR_OFFSET_HP_MAX: equ $C
CHAR_OFFSET_HP_CURRENT: equ $E
CHAR_OFFSET_MP_MAX: equ $10
CHAR_OFFSET_MP_CURRENT: equ $11
CHAR_OFFSET_ATK_MAX: equ $12
CHAR_OFFSET_ATK_CURRENT: equ $13
CHAR_OFFSET_DEF_MAX: equ $14
CHAR_OFFSET_DEF_CURRENT: equ $15
CHAR_OFFSET_AGI_MAX: equ $16
CHAR_OFFSET_AGI_CURRENT: equ $17
CHAR_OFFSET_MOV_MAX: equ $18
CHAR_OFFSET_MOV_CURRENT: equ $19
CHAR_OFFSET_RESIST_BASE: equ $1A
CHAR_OFFSET_RESIST_CURRENT: equ $1C
CHAR_OFFSET_SPECIAL_BASE: equ $1E
CHAR_OFFSET_PROWESS_CURRENT: equ $1F
CHAR_OFFSET_ITEM_0: equ $20
CHAR_OFFSET_ITEM_1: equ $22
CHAR_OFFSET_ITEM_2: equ $24
CHAR_OFFSET_ITEM_3: equ $26
CHAR_OFFSET_SPELL_0: equ $28
CHAR_OFFSET_STATUS: equ $2C
CHAR_OFFSET_X: equ $2E
CHAR_OFFSET_Y: equ $2F
CHAR_OFFSET_EXP: equ $30
CHAR_OFFSET_MOVETYPE: equ $31
CHAR_OFFSET_KILLS: equ $32
CHAR_OFFSET_DEFEATS: equ $36
CHAR_OFFSET_ENEMYIDX: equ $37

; ---------------------------------------------------------------------------

; enum ClassDef
CLASSIDX_BRGN: equ $16

; ---------------------------------------------------------------------------

; enum EnemyAI
ENEMYAI_THRESHOLD_HEAL1: equ $2
ENEMYAI_THRESHOLD_HEAL2: equ $E
ENEMYAI_THRESHOLD_HEAL3: equ $1C

; ---------------------------------------------------------------------------

; enum Icon_Offsets
ICON_OFFSET_CRACKS: equ $6F00

; ---------------------------------------------------------------------------

; enum IconDef_Idx
ICONIDX_NOTHING: equ $7F
ICONIDX_UNARMED: equ $80
ICONIDX_HEAL: equ $82
ICONIDX_JEWEL_OF_LIGHT: equ $92
ICONIDX_JEWEL_OF_EVIL: equ $93

; ---------------------------------------------------------------------------

; enum Controller_Input_A_Bitmap
INPUT_A_UP: equ $0
INPUT_A_DOWN: equ $1
INPUT_A_LEFT: equ $2
INPUT_A_RIGHT: equ $3
INPUT_A_B: equ $4
INPUT_A_C: equ $5
INPUT_A_A: equ $6
INPUT_A_START: equ $7

; ---------------------------------------------------------------------------

; enum ItemDef
ITEM_SELLPRICE_BITSHIFTRIGHT: equ $2
ITEM_SELLPRICE_MULTIPLIER: equ $3
ITEMDEF_OFFSET_MAXRANGE: equ $4
ITEMDEF_OFFSET_MINRANGE: equ $5
ITEMDEF_LIFE_RING_RECOVERY: equ $5
ITEMDEF_OFFSET_PRICE: equ $6
ITEMDEF_OFFSET_TYPE: equ $8
ITEMDEF_OFFSET_SPELL: equ $9
ITEMDEF_OFFSET_STATINFO1: equ $A
ITEM_MAX_IDX: equ $7F

; ---------------------------------------------------------------------------

; enum Deals
DEALS_ADDAMT_EVEN: equ $1
DEALS_MAX_NUM_PER_ITEM: equ $F
DEALS_BIT_REMAINDER: equ $10
DEALS_ADDAMT_ODD: equ $10

; ---------------------------------------------------------------------------

; enum Caravan
CARAVAN_MAX_ITEMS: equ $3F

; ---------------------------------------------------------------------------

; enum ItemDef_Idx
ITEMIDX_ANGEL_WING: equ $4
ITEMIDX_HEALING_RAIN: equ $8
ITEMIDX_POWER_RING: equ $13
ITEMIDX_PROTECT_RING: equ $14
ITEMIDX_QUICK_RING: equ $15
ITEMIDX_RUNNING_RING: equ $16
ITEMIDX_ACHILLES_SWORD: equ $3D
ITEMIDX_COUNTER_SWORD: equ $44
ITEMIDX_IRON_BALL: equ $66
ITEMIDX_GISARME: equ $6D
ITEMIDX_TAROS_SWORD: equ $6E
ITEMIDX_LIFE_RING: equ $7C
ITEMIDX_CHIRRUP_SANDALS: equ $7E
ITEMIDX_NOTHING: equ $7F
ITEMIDX_CHEST_GOLD_AMOUNTS_START: equ $80

; ---------------------------------------------------------------------------

; enum ItemDef_Type_Bitfield
ITEMTYPE_BIT_WEAPON: equ $1
ITEMTYPE_IDX_WEAPON: equ $1
ITEMTYPE_MASK_WEAPON: equ $2
ITEMTYPE_BIT_RING: equ $2
ITEMTYPE_BIT_RARE: equ $3
ITEMTYPE_MASK_RING: equ $4
ITEMTYPE_BIT_UNSELLABLE: equ $4
ITEMTYPE_BIT_CURSED: equ $6
ITEMTYPE_MASK_WEAPONORRING: equ $6
ITEMTYPE_MASK_RARE: equ $8
ITEMTYPE_MASK_UNSELLABLE: equ $10

; ---------------------------------------------------------------------------

; enum ItemEntry
ITEM_OFFSET_IDXANDEQUIPBYTE: equ $1
ITEM_MASK_IDXANDBROKEN: equ $807F

; ---------------------------------------------------------------------------

; enum ItemEntry_Idx
ITEM_IDX_BITSIZE: equ $7

; ---------------------------------------------------------------------------

; enum ItemEntry_Props
ITEM_BIT_EQUIPPED: equ $7
ITEM_UPPERBIT_BROKEN: equ $7
ITEM_BIT_ENEMYUSE: equ $D
ITEM_BIT_BROKEN: equ $F
ITEM_MASK_IDX: equ $7F

; ---------------------------------------------------------------------------

; enum MapDef
MAP_SIZE_MAXHEIGHT: equ $30
MAP_SIZE_MAXWIDTH: equ $30
MAP_BLOCKIDX_CLOSEDCHEST: equ $D801
MAP_BLOCKIDX_OPENCHEST: equ $D802
MAP_NULLPOSITION: equ $FFFF

; ---------------------------------------------------------------------------

; enum Map_Entity
ENTITYDEF_OFFSET_X: equ $0
ENTITYDEF_OFFSET_Y: equ $2
ENTITYDEF_SIZE_BITS: equ $5
ENTITYDEF_OFFSET_XDEST: equ $C
ENTITYDEF_OFFSET_YDEST: equ $E
ENTITYDEF_OFFSET_FACING: equ $10
ENTITYDEF_OFFSET_ENTNUM: equ $12
ENTITYDEF_OFFSET_MAPSPRITE: equ $13
ENTITYDEF_OFFSET_ACTSCRIPTADDR: equ $14
ENTITYDEF_OFFSET_XSPEED: equ $1A
ENTITYDEF_OFFSET_YSPEED: equ $1B
ENTITYDEF_OFFSET_FLAGS_A: equ $1C
ENTITYDEF_OFFSET_FLAGS_B: equ $1D
ENTITYDEF_OFFSET_ANIMCOUNTER: equ $1E
ENTITYDEF_OFFSET_ACTSCRIPTWAITTIMER: equ $1F
ENTITYDEF_SIZE: equ $20
ENTITYIDX_UNITCURSOR: equ $30

; ---------------------------------------------------------------------------

; enum SoundCommands
SOUND_COMMAND_INIT_DRIVER: equ $20
SOUND_COMMAND_WAIT_MUSIC_END: equ $F0
SOUND_COMMAND_PLAY_PREVIOUS_MUSIC: equ $FB
SOUND_COMMAND_FADE_OUT: equ $FD
SOUND_COMMAND_GET_D0_PARAMETER: equ $FFFF

; ---------------------------------------------------------------------------

; enum Music
MUSIC_NOTHING: equ $0
MUSIC_MAIN_THEME: equ $1
MUSIC_ATTACK: equ $2
MUSIC_PROMOTED_ATTACK: equ $3
MUSIC_PROMOTED_ATTACK_LOOP: equ $4
MUSIC_ENEMY_ATTACK: equ $5
MUSIC_BOSS_ATTACK: equ $6
MUSIC_ZEON_ATTACK: equ $7
MUSIC_TOWN: equ $8
MUSIC_INTRO: equ $9
MUSIC_WITCH: equ $A
MUSIC_SUSPEND: equ $B
MUSIC_SAD_THEME_2: equ $C
MUSIC_ELVEN_TOWN: equ $D
MUSIC_MITULA: equ $E
MUSIC_SAD_THEME_3: equ $F
MUSIC_SAD_THEME_1: equ $10
MUSIC_PIANO_THEME: equ $11
MUSIC_CORRUPTED_SAVE: equ $12
MUSIC_JOIN: equ $13
MUSIC_SAD_JOIN: equ $14
MUSIC_SAVE: equ $15
MUSIC_CURE: equ $16
MUSIC_UNUSED_REVIVE: equ $17
MUSIC_REVIVE: equ $18
MUSIC_PROMOTION: equ $19
MUSIC_CURSED_ITEM: equ $1A
MUSIC_ITEM: equ $1B
MUSIC_TITLE: equ $1C
MUSIC_STOP: equ $20
MUSIC_BATTLE_THEME_3: equ $21
MUSIC_BATTLE_THEME_1: equ $22
MUSIC_SHRINE: equ $23
MUSIC_FINAL_BATTLE: equ $24
MUSIC_MITHRIL_DIGGERS: equ $25
MUSIC_CASTLE: equ $26
MUSIC_HEADQUARTERS: equ $27
MUSIC_MITULA_SHRINE: equ $28
MUSIC_ENDING: equ $29

; ---------------------------------------------------------------------------

; enum Sfx
SFX_MENU_SWITCH: equ $41
SFX_MENU_SELECTION: equ $42
SFX_VALIDATION: equ $43
SFX_REFUSAL: equ $44
SFX_DIALOG_BLEEP_1: equ $45
SFX_DIALOG_BLEEP_2: equ $46
SFX_DIALOG_BLEEP_3: equ $47
SFX_DIALOG_BLEEP_4: equ $48
SFX_DIALOG_BLEEP_5: equ $49
SFX_DIALOG_BLEEP_6: equ $4A
SFX_DIALOG_BLEEP_7: equ $4B
SFX_DIALOG_BLEEP_8: equ $4C
SFX_SPELL_CAST: equ $4D
SFX_DOOR_OPEN_HIGH_PITCH: equ $4E
SFX_WALKING: equ $4F
SFX_UNUSED_FROM_LANDSTALKER: equ $50
SFX_LIGHTNING_1: equ $51
SFX_LIGHTNING_2: equ $52
SFX_HIT_1: equ $53
SFX_HIT_2: equ $54
SFX_BLAST: equ $55
SFX_SWORDS_HIT: equ $56
SFX_JUMP: equ $57
SFX_FALLING: equ $58
SFX_WARP: equ $59
SFX_CHIRRUP_SANDALS: equ $5A
SFX_MONSTER_DIALOG_BLEEP: equ $5B
SFX_DOOR_OPEN: equ $5C
SFX_BIG_DOOR_RUMBLE: equ $5D
SFX_MONSTER_SCREAM: equ $5E
SFX_BUUBOBI: equ $5F
SFX_SECRET_PATH_ROCK: equ $60
SFX_PSH: equ $61
SFX_PSHHH: equ $62
SFX_BLOAB: equ $63
SFX_BLO: equ $64
SFX_LANDSTALKER_ITEM: equ $65
SFX_LEVEL_UP: equ $66
SFX_PRISM_LASER_LOADING: equ $67
SFX_LANDSTALKER_SWITCH: equ $68
SFX_SFCD_STATUES: equ $69
SFX_DESOUL: equ $6A
SFX_SITD_HOWL: equ $6B
SFX_PRISM_LASER_FIRING: equ $6C
SFX_BOOST: equ $6D
SFX_DESOUL_HOVERING: equ $6E
SFX_PRISM_LASER_CUTSCENE_FIRING: equ $6F
SFX_TAROS_DIALOG_BLEEP: equ $70
SFX_HEALING: equ $71
SFX_BLAST_SPELL: equ $72
SFX_WING_FLAP: equ $73
SFX_BATTLEFIELD_DEATH: equ $74
SFX_DEMON_BREATH: equ $75
SFX_INTRO_LIGHTNING: equ $76
SFX_BOLT_SPELL: equ $77
SFX_TINKLING: equ $78

; ---------------------------------------------------------------------------

; enum SpellDef
SPELLDEF_OFFSET_MPCOST: equ $1
SPELLDEF_OFFSET_ANIMIDX: equ $2
SPELLDEF_OFFSET_PROPS: equ $3
SPELLDEF_OFFSET_MAXRANGE: equ $4
SPELLDEF_OFFSET_MINRANGE: equ $5
SPELLDEF_OFFSET_RADIUS: equ $6
SPELLDEF_OFFSET_POWER: equ $7
SPELLDEF_SIZE: equ $8
MAX_SPELL_IDX: equ $3F

; ---------------------------------------------------------------------------

; enum SpellDef_Props
SPELLDEF_TYPE_ATTACK: equ $0
SPELLDEF_TYPE_HEAL: equ $1
SPELLDEF_RESIST_MINOR: equ $1
SPELLDEF_TYPE_STATUS: equ $2
SPELLDEF_RESIST_MAJOR: equ $2
SPELLDEF_PROPS_TYPE_MASK: equ $3
SPELLDEF_RESIST_WEAKNESS: equ $3
SPELLDEF_LEVELS_NUM: equ $4
SPELLDEF_PROPS_BIT_AFFECTEDBYSILENCE: equ $7

; ---------------------------------------------------------------------------

; enum SpellDef_Idx
SPELLIDX_DESOUL: equ $8
SPELLIDX_EGRESS: equ $A
SPELLIDX_BLAZE: equ $B
SPELLIDX_FREEZE: equ $C
SPELLIDX_BOLT: equ $D
SPELLIDX_BLAST: equ $E
SPELLIDX_KATON: equ $1B
SPELLIDX_RAIJIN: equ $1C
SPELLIDX_DAO: equ $1D
SPELLIDX_APOLLO: equ $1E
SPELLIDX_NEPTUN: equ $1F
SPELLIDX_ATLAS: equ $20
SPELLIDX_NOTHING: equ $3F

; ---------------------------------------------------------------------------

; enum SpellEntry
SPELL_OFFSET_IDX: equ $0
SPELL_MASK_RESIST: equ $3
SPELL_OFFSET_LV: equ $6
SPELL_IDX_REALMASK: equ $3F
SPELL_DEFS_COUNTER: equ $63
SPELL_MASK_LV: equ $C0
SPELL_MASK: equ $FF
SPELL_MASK_ALLRESIST: equ $C0FF

; ---------------------------------------------------------------------------

; enum SpellEntry_Idx
SPELL_IDX_BITSIZE: equ $6
SPELL_MASK_IDX: equ $3F

; ---------------------------------------------------------------------------

; enum SpellEntry_LV
SPELL_LV_BITSIZE: equ $2
SPELL_UPPERMASK_LV: equ $3

; ---------------------------------------------------------------------------

; enum Battle
ACTION_ATTACK: equ $0
ACTION_SPELL: equ $1
ACTION_ITEM: equ $2
ACTION_BURSTROCK: equ $4
BATTLE_INACTIONCHANCEDIVISOR_CURSE: equ $4
BATTLE_INACTIONCHANCEDIVISOR_STUN: equ $4
ACTION_NOTHING: equ $5
ACTION_PRISMLASER: equ $6
BATTLEIDX_TAROS: equ $12
MAX_BTL_IDX: equ $2C
BATTLEIDX_FAIRY_WOODS: equ $2C

; ---------------------------------------------------------------------------

; enum Battle_Cutscene
BTLANIM_ATTACK: equ $0
BTLANIM_DODGE: equ $1
BTLANIM_EFFECT: equ $2
BTLSCENE_ACTION_OFFSET_ITEMORSPELL: equ $2
BTLANIM_RANGED: equ $6
BTLSCENE_STACKNEGSIZE: equ $FF68

; ---------------------------------------------------------------------------

; enum Battle_Cutscene_Stack
BCSTACK_OFFSET_CUTOFF: equ $1
BCSTACK_OFFSET_CRIT: equ $3
BCSTACK_OFFSET_TARGETDIES: equ $4
BCSTACK_OFFSET_DODGE: equ $5
BCSTACK_OFFSET_RANGED: equ $6
BCSTACK_OFFSET_SAMESIDE: equ $7
BCSTACK_OFFSET_MUDDLED: equ $8
BCSTACK_OFFSET_INACTION_CURSE: equ $9
BCSTACK_OFFSET_INACTION_STUN: equ $A
BCSTACK_OFFSET_SILENCED: equ $B
BCSTACK_OFFSET_COUNTER: equ $C
BCSTACK_OFFSET_DOUBLE: equ $D
BCSTACK_OFFSET_INEFFECTIVEATTACK: equ $E
BCSTACK_OFFSET_EXPLODE: equ $10
BCSTACK_OFFSET_EXPLODECHAR: equ $11
BCSTACK_OFFSET_DEBUGCOUNTER: equ $14
BCSTACK_OFFSET_DEBUGDOUBLE: equ $15
BCSTACK_OFFSET_DEBUGCRIT: equ $16
BCSTACK_OFFSET_DEBUGDODGE: equ $17

; ---------------------------------------------------------------------------

; enum Def_Lengths
SIZE_ITEM: equ $2
BITS_HALFBYTE: equ $4
SIZE_ITEMDEF: equ $10

; ---------------------------------------------------------------------------

; enum Flags
FLAG_COUNT_FORCEMEMBERS_JOINED: equ $20
FLAGIDX_RAFT: equ $40
FLAGIDX_FOLLOWERS_ASTRAL: equ $46
FLAGIDX_BTLCUTSCENE_GIZMOS: equ $18F
FLAGIDX_BATTLE0: equ $190
FLAG_MASK: equ $3FF

; ---------------------------------------------------------------------------

; enum Codes
CODE_NOTHING_BYTE: equ $FF
CODE_TERMINATOR_BYTE: equ $FF
CODE_NOTHING_WORD: equ $FFFF
CODE_TERMINATOR_WORD: equ $FFFF

; ---------------------------------------------------------------------------

; enum Special_Offsets
NRO: equ $FF000000

; ---------------------------------------------------------------------------

; enum Text_Index
TEXTIDX_CHANGEYOURMIND: equ $4
TEXTIDX_HQ: equ $2E
TEXTIDX_CARAVANDESC_ITEMHASEFFECT: equ $5D
TEXTIDX_CARAVANDESC_ITEMHASNOEFFECT: equ $5E
TEXTIDX_CARAVANDESC_EVERYBODY: equ $5F
TEXTIDX_CARAVANDESC_ITEMISFOR: equ $60
TEXTIDX_CARAVANDESC_ITEMFORNOBODY: equ $61
TEXTIDX_CARAVANDESC_ITEMFORNAME: equ $62
TEXTIDX_CARAVANDESC_NEWLINE: equ $63
TEXTIDX_CARAVANDESC_TOEQUIP: equ $64
TEXTIDX_CARAVANDESC_SELLPRICE: equ $65
TEXTIDX_CARAVANDESC_UNSELLABLE: equ $66
TEXTIDX_BATTLE_DAMAGE_ALLY: equ $11C
TEXTIDX_BATTLE_DAMAGE_ENEMY: equ $11D
TEXTIDX_BATTLE_DODGE: equ $11E
TEXTIDX_BATTLE_CRITDAMAGE: equ $11F
TEXTIDX_BATTLE_HEAVYDAMAGE: equ $120
TEXTIDX_BATTLE_INEFFECTIVEATTACK: equ $121
TEXTIDX_BATTLE_CUTOFF: equ $126
TEXTIDX_BATTLE_SILENCED: equ $128
TEXTIDX_BATTLE_CURSEDSTUNNED: equ $167
TEXTIDX_BATTLE_STUNNED: equ $169
TEXTIDX_BATTLE_PICKEDUPITEM: equ $18B
TEXTIDX_BATTLE_DROPPEDITEM: equ $18C
TEXTIDX_END: equ $FFFF

; ---------------------------------------------------------------------------

; enum Windowing
WINDOW_DIALOGUE_TILELINECOUNTER_BATTLE: equ $3
WINDOW_NUMPROMPT_STACK_OFFSET_WINDOWTILESEND: equ $4
WINDOW_DIALOGUE_TILELINECOUNTER_EVENT: equ $5
WINDOW_MEMBER_KD_TEXT_DEFEATS_LENGTH: equ $6
WINDOW_MEMBER_KD_TEXT_KILLS_LENGTH: equ $6
WINDOW_NUMPROMPT_STACK_OFFSET_WINDOWIDX: equ $6
WINDOW_NUMPROMPT_STACK_OFFSET_NUM: equ $8
WINDOW_NUMPROMPT_STACK_OFFSET_MINNUM: equ $A
WINDOW_NUMPROMPT_STACK_OFFSET_MAXNUM: equ $C
WINDOW_NUMPROMPT_STACK_NEGSIZE: equ $10
WINDOW_DIALOGUE_WIDTHINTILES: equ $1A
WINDOW_MEMBER_KD_TEXT_DEFEATS_OFFSET: equ $24
WINDOW_MEMBER_STATS_TEXT_CLASS_OFFSET: equ $2C
WINDOW_MEMBER_KD_TEXT_KILLS_OFFSET: equ $72
WINDOW_MEMBER_KD_VDPTILEORDER_BYTESIZE: equ $C0
WINDOW_MEMBER_PORTRAIT_POSITION: equ $201
WINDOW_MEMBER_KD_POSITION: equ $20B
WINDOW_MEMBER_GOLD_POSITION: equ $217
WINDOW_MEMBER_STATS_VDPTILEORDER_BYTESIZE: equ $444
WINDOW_MEMBER_PORTRAIT_SIZE: equ $80A
WINDOW_MEMBER_KD_SIZE: equ $80C
WINDOW_MEMBER_GOLD_SIZE: equ $80C
WINDOW_MEMBER_STATS_POSITION: equ $A01
WINDOW_MEMBER_STATS_SIZE: equ $151A
WINDOW_MEMBER_STATS_DEST: equ $2001
WINDOW_MEMBER_KD_DEST: equ $F80B
WINDOW_MEMBER_GOLD_DEST: equ $F81C
WINDOW_MEMBER_PORTRAIT_DEST: equ $F8F6

; ---------------------------------------------------------------------------

; enum Text
TEXT_CODE_NEWLINE: equ $B
TEXT_CODE_MOVEDOWN: equ $D
TEXT_CODE_TOGGLEFONTCOLOR: equ $5C

; ---------------------------------------------------------------------------

; enum VDP_Tile
VDPTILE_PALETTE3_MASK: equ $C000
VDPTILE_IDX_DIALOGUEWINDOW_TOPLEFTBORDER: equ $C060
VDPTILE_IDX_DIALOGUEWINDOW_TOPBORDER: equ $C061
VDPTILE_IDX_DIALOGUEWINDOW_LEFTBORDER: equ $C070
VDPTILE_IDX_DIALOGUEWINDOW_FIRSTINNERBOXTILE: equ $C640
VDPTILE_IDX_SCREEN_BLACKBAR: equ $C77C
VDPTILE_IDX_DIALOGUEWINDOW_TOPRIGHTBORDER: equ $C860
VDPTILE_IDX_DIALOGUEWINDOW_RIGHTBORDER: equ $C870
VDPTILE_STATUSEFFECT_CURSE: equ $C0ECC0ED

; ---------------------------------------------------------------------------

; enum Status_Effects
STATUSEFFECT_LASTING_EFFECTS_MASK: equ $7

; ---------------------------------------------------------------------------

; enum Gold
GOLD_STARTING_AMOUNT: equ $3C

; ---------------------------------------------------------------------------

; enum WindowProperties
ACTIVE: equ $0
LAYOUT_OFFSET: equ $2
WIDTH: equ $4
HEIGHT: equ $5
X: equ $6
Y: equ $7
ANIM_ORIG_X: equ $8
ANIM_ORIG_Y: equ $9
ANIM_DEST_X: equ $A
ANIM_DEST_Y: equ $B
ANIM_LENGTH: equ $C
ANIM_COUNTER: equ $D

; ---------------------------------------------------------------------------

; enum Fading
IN_FROM_BLACK: equ $1
OUT_TO_BLACK: equ $2
IN_FROM_WHITE: equ $3
OUT_TO_WHITE: equ $4
PULSATING_1: equ $5
PULSATING_2: equ $6
FLASH_QUICKLY_1: equ $7
NOTHING: equ $8
HALF_OUT_TO_BLACK: equ $9
FLICKER_ONCE: equ $A
FLASH_QUICKLY_2: equ $B
INSTANT_BLACK: equ $C
NOTHING_2: equ $D
HALF_IN_FROM_BLACK: equ $E
OUT_TO_BLACK_2: equ $F

; ---------------------------------------------------------------------------

; enum Direction
RIGHT: equ $0
UP: equ $1
LEFT: equ $2
DOWN: equ $3
NO_DIRECTION: equ $FF

; ---------------------------------------------------------------------------

; enum Mapsprites
MAPSPRITE_BOWIE_BASE: equ $0
MAPSPRITE_BOWIE_PROMO: equ $1
MAPSPRITE_SARAH_BASE: equ $2
MAPSPRITE_SARAH_PROMO: equ $3
MAPSPRITE_SARAH_SPECIAL: equ $4
MAPSPRITE_CHESTER_BASE: equ $5
MAPSPRITE_CHESTER_PROMO: equ $6
MAPSPRITE_CHESTER_SPECIAL: equ $7
MAPSPRITE_JAHA_BASE: equ $8
MAPSPRITE_JAHA_PROMO: equ $9
MAPSPRITE_JAHA_SPECIAL: equ $A
MAPSPRITE_KAZIN_BASE: equ $B
MAPSPRITE_KAZIN_PROMO: equ $C
MAPSPRITE_KAZIN_SPECIAL: equ $D
MAPSPRITE_SLADE_BASE: equ $E
MAPSPRITE_SLADE_PROMO: equ $F
MAPSPRITE_KIWI_BASE: equ $10
MAPSPRITE_KIWI_PROMO: equ $11
MAPSPRITE_PETER_BASE: equ $12
MAPSPRITE_PETER_PROMO: equ $13
MAPSPRITE_MAY_BASE: equ $14
MAPSPRITE_MAY_PROMO: equ $15
MAPSPRITE_GERHALT_BASE: equ $16
MAPSPRITE_GERHALT_PROMO: equ $17
MAPSPRITE_LUKE_BASE: equ $18
MAPSPRITE_LUKE_PROMO: equ $19
MAPSPRITE_ROHDE_SPECIAL: equ $1A
MAPSPRITE_RICK_BASE: equ $1B
MAPSPRITE_RICK_PROMO: equ $1C
MAPSPRITE_RICK_SPECIAL: equ $1D
MAPSPRITE_ELRIC_BASE: equ $1E
MAPSPRITE_ELRIC_PROMO: equ $1F
MAPSPRITE_ELRIC_SPECIAL: equ $20
MAPSPRITE_ERIC_BASE: equ $21
MAPSPRITE_ERIC_PROMO: equ $22
MAPSPRITE_ERIC_SPECIAL: equ $23
MAPSPRITE_KARNA_BASE: equ $24
MAPSPRITE_KARNA_PROMO: equ $25
MAPSPRITE_KARNA_SPECIAL: equ $26
MAPSPRITE_RANDOLF_BASE: equ $27
MAPSPRITE_RANDOLF_PROMO: equ $28
MAPSPRITE_RANDOLF_SPECIAL: equ $29
MAPSPRITE_TYRIN_BASE: equ $2A
MAPSPRITE_TYRIN_PROMO: equ $2B
MAPSPRITE_TYRIN_SPECIAL: equ $2C
MAPSPRITE_JANET_BASE: equ $2D
MAPSPRITE_JANET_PROMO: equ $2E
MAPSPRITE_JANET_SPECIAL: equ $2F
MAPSPRITE_HIGINS_PROMO: equ $30
MAPSPRITE_SKREECH_PROMO: equ $31
MAPSPRITE_TAYA_SPECIAL: equ $32
MAPSPRITE_FRAYJA_PROMO: equ $33
MAPSPRITE_JARO_SPECIAL: equ $34
MAPSPRITE_GYAN_PROMO: equ $35
MAPSPRITE_SHEELA_SPECIAL: equ $36
MAPSPRITE_ZYNK_PROMO: equ $37
MAPSPRITE_CHAZ_PROMO: equ $38
MAPSPRITE_LEMON_SPECIAL: equ $39
MAPSPRITE_CLAUDE_PROMO: equ $3A
MAPSPRITE_POSE1: equ $3B
MAPSPRITE_BLANK: equ $3C
MAPSPRITE_RAFT: equ $3D
MAPSPRITE_CARAVAN: equ $3E
MAPSPRITE_EFFECT1: equ $3F
MAPSPRITE_OOZE: equ $40
MAPSPRITE_HUGE_RAT: equ $41
MAPSPRITE_GALAM_SOLDIER: equ $42
MAPSPRITE_GALAM_KNIGHT: equ $43
MAPSPRITE_GOBLIN: equ $44
MAPSPRITE_GREEN_OOZE: equ $45
MAPSPRITE_DARK_DWARF: equ $46
MAPSPRITE_HOBGOBLIN: equ $47
MAPSPRITE_ZOMBIE: equ $48
MAPSPRITE_GOLEM: equ $49
MAPSPRITE_KRAKEN_LEG: equ $4A
MAPSPRITE_SOULSOWER: equ $4B
MAPSPRITE_ORC: equ $4C
MAPSPRITE_PAWN: equ $4D
MAPSPRITE_KNIGHT: equ $4E
MAPSPRITE_RAT: equ $4F
MAPSPRITE_BUBBLING_OOZE: equ $50
MAPSPRITE_SKELETON: equ $51
MAPSPRITE_DARK_SOLDIER: equ $52
MAPSPRITE_LIZARDMAN: equ $53
MAPSPRITE_WORM: equ $54
MAPSPRITE_DARK_KNIGHT: equ $55
MAPSPRITE_ORC_LORD: equ $56
MAPSPRITE_DEVIL_SOLDIER: equ $57
MAPSPRITE_CERBERUS: equ $58
MAPSPRITE_MUD_MAN: equ $59
MAPSPRITE_DRAGONEWT: equ $5A
MAPSPRITE_PURPLE_WORM: equ $5B
MAPSPRITE_EXECUTIONER: equ $5C
MAPSPRITE_HELL_HOUND: equ $5D
MAPSPRITE_MINOTAUR: equ $5E
MAPSPRITE_CYCLOPS: equ $5F
MAPSPRITE_BURST_ROCK: equ $60
MAPSPRITE_HYDRA: equ $61
MAPSPRITE_CHAOS_WARRIOR: equ $62
MAPSPRITE_REAPER: equ $63
MAPSPRITE_EVIL_BEAST: equ $64
MAPSPRITE_PYROHYDRA: equ $65
MAPSPRITE_ZEON_GUARD: equ $66
MAPSPRITE_GIZMO: equ $67
MAPSPRITE_HUGE_BAT: equ $68
MAPSPRITE_VAMPIRE_BAT: equ $69
MAPSPRITE_EVIL_CLOUD: equ $6A
MAPSPRITE_GARGOYLE: equ $6B
MAPSPRITE_HARPY: equ $6C
MAPSPRITE_LESSER_DEMON: equ $6D
MAPSPRITE_WYVERN: equ $6E
MAPSPRITE_HARPY_QUEEN: equ $6F
MAPSPRITE_PEGASUS_KNIGHT: equ $70
MAPSPRITE_GRIFFIN: equ $71
MAPSPRITE_MIST_DEMON: equ $72
MAPSPRITE_WHITE_DRAGON: equ $73
MAPSPRITE_DEMON: equ $74
MAPSPRITE_CHAOS_DRAGON: equ $75
MAPSPRITE_DEVIL_GRIFFIN: equ $76
MAPSPRITE_ARCH_DEMON: equ $77
MAPSPRITE_GALAM_ARCHER: equ $78
MAPSPRITE_HUNTER_GOBLIN: equ $79
MAPSPRITE_DEATH_ARCHER: equ $7A
MAPSPRITE_KRAKEN_ARM: equ $7B
MAPSPRITE_ARROW_LAUNCHER: equ $7C
MAPSPRITE_ROOK: equ $7D
MAPSPRITE_DARK_SNIPER: equ $7E
MAPSPRITE_BOW_MASTER: equ $7F
MAPSPRITE_BOW_RIDER: equ $80
MAPSPRITE_DARK_GUNNER: equ $81
MAPSPRITE_HORSEMAN: equ $82
MAPSPRITE_GALAM_MAGE: equ $83
MAPSPRITE_WITCH: equ $84
MAPSPRITE_MASTER_MAGE: equ $85
MAPSPRITE_DARK_MADAM: equ $86
MAPSPRITE_QUEEN: equ $87
MAPSPRITE_WIZARD: equ $88
MAPSPRITE_NECROMANCER: equ $89
MAPSPRITE_CHAOS_WIZARD: equ $8A
MAPSPRITE_DEMON_MASTER: equ $8B
MAPSPRITE_DARK_CLERIC: equ $8C
MAPSPRITE_DEATH_MONK: equ $8D
MAPSPRITE_BLACK_MONK: equ $8E
MAPSPRITE_HIGH_PRIEST: equ $8F
MAPSPRITE_EVIL_BISHOP: equ $90
MAPSPRITE_DARK_BISHOP: equ $91
MAPSPRITE_MASTER_MONK: equ $92
MAPSPRITE_SHAMAN: equ $93
MAPSPRITE_BLUE_SHAMAN: equ $95
MAPSPRITE_DARK_SMOKE: equ $96
MAPSPRITE_FILLER1: equ $97
MAPSPRITE_FILLER2: equ $98
MAPSPRITE_KING: equ $99
MAPSPRITE_WILLARD: equ $9A
MAPSPRITE_ZALBARD: equ $9B
MAPSPRITE_CAMEELA: equ $9C
MAPSPRITE_PRISM_FLOWER: equ $9D
MAPSPRITE_RED_BARON: equ $9E
MAPSPRITE_GESHP: equ $9F
MAPSPRITE_ODD_EYE: equ $A0
MAPSPRITE_FILLER3: equ $A1
MAPSPRITE_FILLER4: equ $A2
MAPSPRITE_GALAM_ZEON: equ $A3
MAPSPRITE_GALAM_EVIL: equ $A4
MAPSPRITE_FILLER5: equ $A5
MAPSPRITE_FILLER6: equ $A6
MAPSPRITE_FILLER7: equ $A7
MAPSPRITE_FILLER8: equ $A8
MAPSPRITE_FILLER9: equ $A9
MAPSPRITE_NPC_ROHDE: equ $AA
MAPSPRITE_FLAME1: equ $AB
MAPSPRITE_ORB: equ $AC
MAPSPRITE_OBJECT1: equ $AD
MAPSPRITE_POSE2: equ $AE
MAPSPRITE_EFFECT2: equ $AF
MAPSPRITE_POSE3: equ $B0
MAPSPRITE_POSE4: equ $B1
MAPSPRITE_EFFECT3: equ $B2
MAPSPRITE_OBJECT2: equ $B3
MAPSPRITE_OBJECT3: equ $B4
MAPSPRITE_OBJECT4: equ $B5
MAPSPRITE_CHICK_Flying: equ $B6
MAPSPRITE_EFFECT4: equ $B7
MAPSPRITE_POSE5: equ $B8
MAPSPRITE_ZELOT: equ $B9
MAPSPRITE_EFFECT5: equ $BA
MAPSPRITE_EFFECT6: equ $BB
MAPSPRITE_DESKTOP_KING: equ $BC
MAPSPRITE_HAWEL: equ $BD
MAPSPRITE_BLUE_FLAME: equ $BE
MAPSPRITE_FILLER10: equ $BF
MAPSPRITE_PRIEST: equ $C0
MAPSPRITE_SAILOR: equ $C1
MAPSPRITE_MAN1: equ $C2
MAPSPRITE_WOMAN1: equ $C3
MAPSPRITE_MAN2: equ $C4
MAPSPRITE_WOMAN2: equ $C5
MAPSPRITE_MAN3: equ $C6
MAPSPRITE_WOMAN3: equ $C7
MAPSPRITE_BOY: equ $C8
MAPSPRITE_GIRL: equ $C9
MAPSPRITE_WORKER: equ $CA
MAPSPRITE_GRANSEAL_KING: equ $CB
MAPSPRITE_ELIS: equ $CC
MAPSPRITE_MINISTER: equ $CD
MAPSPRITE_SOLDIER1: equ $CE
MAPSPRITE_SOLDIER2: equ $CF
MAPSPRITE_MAID: equ $D0
MAPSPRITE_ASTRAL: equ $D1
MAPSPRITE_CAT: equ $D2
MAPSPRITE_BOAT: equ $D3
MAPSPRITE_CREED: equ $D4
MAPSPRITE_ODDLER: equ $D5
MAPSPRITE_GALAM_KING: equ $D6
MAPSPRITE_MITULA: equ $D7
MAPSPRITE_POSE6: equ $D8
MAPSPRITE_POSE7: equ $D9
MAPSPRITE_DUCK: equ $DA
MAPSPRITE_FAIRY: equ $DB
MAPSPRITE_BEASTMAN1: equ $DC
MAPSPRITE_TURTLE: equ $DD
MAPSPRITE_BEASTMAN2: equ $DE
MAPSPRITE_ELF_BOY: equ $DF
MAPSPRITE_ELF_GIRL: equ $E0
MAPSPRITE_VIKING: equ $E1
MAPSPRITE_DWARF: equ $E2
MAPSPRITE_BEDOE_KING: equ $E3
MAPSPRITE_BEDOE_MINISTER: equ $E4
MAPSPRITE_BEDOE_SOLDIER: equ $E5
MAPSPRITE_CHICK: equ $E6
MAPSPRITE_POCALON_KING: equ $E7
MAPSPRITE_POCALON_PRINCESS: equ $E8
MAPSPRITE_POCALON_SOLDIER: equ $E9
MAPSPRITE_POCALON_MAID: equ $EA
MAPSPRITE_HEN: equ $EB
MAPSPRITE_BIRDMAN: equ $EC
MAPSPRITE_END_LIST: equ $ED
MAPSPRITE_FREE_SPOT1: equ $EE
MAPSPRITE_FREE_SPOT2: equ $EF
MAPSPRITE_SPECIAL0: equ $F0
MAPSPRITE_SPECIAL1: equ $F1
MAPSPRITE_SPECIAL2: equ $F2
MAPSPRITE_SPECIAL3: equ $F3
MAPSPRITE_SPECIAL4: equ $F4
MAPSPRITE_SPECIAL5: equ $F5
MAPSPRITE_SPECIAL6: equ $F6
MAPSPRITE_SPECIAL7: equ $F7
MAPSPRITE_SPECIAL8: equ $F8
MAPSPRITE_SPECIAL9: equ $F9
MAPSPRITE_SPECIAL10: equ $FA
MAPSPRITE_ZEON: equ $FB
MAPSPRITE_EVIL_SPIRIT: equ $FC
MAPSPRITE_NAZCA_SHIP: equ $FD
MAPSPRITE_KRAKEN: equ $FE
MAPSPRITE_TAROS: equ $FF

; ---------------------------------------------------------------------------

; enum Allies
ALLY_BOWIE: equ $0
ALLY_SARAH: equ $1
ALLY_CHESTER: equ $2
ALLY_JAHA: equ $3
ALLY_KAZIN: equ $4
ALLY_SLADE: equ $5
ALLY_KIWI: equ $6
ALLY_PETER: equ $7
ALLY_MAY: equ $8
ALLY_GERHALT: equ $9
ALLY_LUKE: equ $A
ALLY_ROHDE: equ $B
ALLY_RICK: equ $C
ALLY_ELRIC: equ $D
ALLY_ERIC: equ $E
ALLY_KARNA: equ $F
ALLY_RANDOLF: equ $10
ALLY_TYRIN: equ $11
ALLY_JANET: equ $12
ALLY_HIGINS: equ $13
ALLY_SKREECH: equ $14
ALLY_TAYA: equ $15
ALLY_FRAYJA: equ $16
ALLY_JARO: equ $17
ALLY_GYAN: equ $18
ALLY_SHEELA: equ $19
ALLY_ZYNK: equ $1A
ALLY_CHAZ: equ $1B
ALLY_LEMON: equ $1C
ALLY_CLAUDE: equ $1D