
; SCRIPT SECTION mapsetups\map16\s1_212 :
; 
ms_map16_flag212_Entities:
										dc.b $2E
										dc.b $B
										dc.b 1
										dc.b $C4
										dc.l eas_Init           
										dc.b $2E
										dc.b $11
										dc.b 1
										dc.b $C4
										dc.l eas_Init           
										dc.b $24
										dc.b $1C
										dc.b 3
										dc.b $C5
										dc.b $FF
										dc.b $24
										dc.b $1C
										dc.b 1
										dc.b $17
										dc.b $1B
										dc.b 1
										dc.b $C5
										dc.l eas_Init           
										dc.b $22
										dc.b $C
										dc.b 2
										dc.b $C5
										dc.l eas_Init           
										dc.b $1B
										dc.b $13
										dc.b 3
										dc.b $C3
										dc.l eas_Init           
										dc.b $20
										dc.b $13
										dc.b 3
										dc.b $C6
										dc.l eas_Init           
										dc.b $2D
										dc.b $F
										dc.b 3
										dc.b $C2
										dc.b $FF
										dc.b $2D
										dc.b $F
										dc.b 1
										dc.b $F
										dc.b $1C
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $23
										dc.b $18
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $1B
										dc.b 5
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b $12
										dc.b $13
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $12
										dc.b $13
										dc.b 1
										dc.b 3
										dc.b $D
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b 3
										dc.b $D
										dc.b 1
										dc.b 7
										dc.b $14
										dc.b 3
										dc.b $CF
										dc.b $FF
										dc.b 7
										dc.b $14
										dc.b 1
										dc.b $17
										dc.b $18
										dc.b 3
										dc.b $AC
										dc.l eas_Init3          
										dc.b $27
										dc.b $18
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $11
										dc.b $A
										dc.b 3
										dc.b $CF
										dc.l eas_Init           
										dc.b $1D
										dc.b $17
										dc.b 3
										dc.b $3E
										dc.l eas_Init           
										dc.w $FFFF
