
; SCRIPT SECTION maps\entries\map13\mapsetups\s1 :
; 
ms_map13_Entities:  dc.b $17
										dc.b $D
										dc.b 3
										dc.b 9
										dc.l eas_Init           
										dc.b $D
										dc.b $1B
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $D
										dc.b $1B
										dc.b 2
										dc.b 6
										dc.b $15
										dc.b 3
										dc.b $EA
										dc.b $FF
										dc.b 6
										dc.b $15
										dc.b 2
										dc.b 1
										dc.b $B
										dc.b 3
										dc.b $DD
										dc.l eas_Init2          
										dc.b 4
										dc.b 7
										dc.b 0
										dc.b $C1
										dc.l eas_Init           
										dc.b 8
										dc.b 7
										dc.b 2
										dc.b $C1
										dc.l eas_Init           
										dc.b $17
										dc.b 6
										dc.b 0
										dc.b $DC
										dc.l eas_Init           
										dc.b $12
										dc.b $17
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b $B
										dc.b $D
										dc.b 0
										dc.b $DC
										dc.b $FF
										dc.b $B
										dc.b $D
										dc.b 2
										dc.b $1A
										dc.b $11
										dc.b 2
										dc.b $DC
										dc.b $FF
										dc.b $1A
										dc.b $11
										dc.b 2
										dc.b $F
										dc.b 3
										dc.b 3
										dc.b $C2
										dc.l eas_Init           
										dc.b $26
										dc.b 6
										dc.b 1
										dc.b $E2
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $4C
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $D5
										dc.l eas_Init           
										dc.w $FFFF
