
; SCRIPT SECTION mapsetups\map02\s1_212 :
; 
ms_map2_flag212_Entities:
										dc.b $16
										dc.b $19
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $16
										dc.b $19
										dc.b 1
										dc.b $29
										dc.b $1A
										dc.b 1
										dc.b $E9
										dc.l eas_Init           
										dc.b $1E
										dc.b $11
										dc.b 0
										dc.b $E9
										dc.l eas_Init           
										dc.b 8
										dc.b $15
										dc.b 0
										dc.b $EA
										dc.l eas_Init           
										dc.b $22
										dc.b 7
										dc.b 3
										dc.b $EA
										dc.b $FF
										dc.b $22
										dc.b 7
										dc.b 1
										dc.b $15
										dc.b 7
										dc.b 3
										dc.b $E9
										dc.l eas_Init           
										dc.b 9
										dc.b 8
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $F
										dc.b 5
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $29
										dc.b 8
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.w $FFFF
