
; SCRIPT SECTION mapsetups\map44\s1_1FB :
; 
ms_map44_flag1FB_Entities:
										dc.b $A
										dc.b 8
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $17
										dc.b 7
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $1E
										dc.b 9
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $C
										dc.b $A
										dc.b 1
										dc.b $C6
										dc.l eas_Init           
										dc.b $D
										dc.b $A
										dc.b 1
										dc.b $C7
										dc.l eas_Init           
										dc.b $E
										dc.b $A
										dc.b 1
										dc.b $C8
										dc.l eas_Init           
										dc.b $C
										dc.b $B
										dc.b 1
										dc.b $C7
										dc.l eas_Init           
										dc.b $D
										dc.b $B
										dc.b 1
										dc.b $C4
										dc.l eas_Init           
										dc.b $E
										dc.b $B
										dc.b 1
										dc.b $C5
										dc.l eas_Init           
										dc.b $14
										dc.b $C
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $A
										dc.b $E
										dc.b 0
										dc.b $C6
										dc.l eas_Init           
										dc.b 8
										dc.b $17
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $E
										dc.b $17
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.w $FFFF
