
; SCRIPT SECTION mapsetups\mapsetupstable :
; Map setups table
MapSetups:          dc.w 3                  ; list of map event addresses and flags to check
										dc.l ms_map3
										dc.w $261
										dc.l ms_map3_flag261
										dc.w $1FA
										dc.l ms_map3_flag1FA
										dc.w $21F
										dc.l ms_map3_flag21F
										dc.w $FFFD
										dc.w 4                  ; for map 4
										dc.l ms_map4
										dc.w $FFFD
										dc.w 5                  ; map 5
										dc.l ms_map5
										dc.w $28A
										dc.l ms_map5_flag28A
										dc.w $212
										dc.l ms_map5_flag212
										dc.w $1C
										dc.l ms_map5_flag1C
										dc.w $FFFD
										dc.w 6
										dc.l ms_map6
										dc.w $2BD
										dc.l ms_map6_flag2BD
										dc.w $2BE
										dc.l ms_map6_flag2BE
										dc.w $FFFD
										dc.w 7
										dc.l ms_map7_flag2BE
										dc.w $2BD
										dc.l ms_map7_flag2BD
										dc.w $2BE
										dc.l ms_map7_flag2BE
										dc.w $325
										dc.l ms_map7_flag325
										dc.w $FFFD
										dc.w 8
										dc.l ms_map8
										dc.w $2C4
										dc.l ms_map8_flag2C4
										dc.w $FFFD
										dc.w 9
										dc.l ms_map9
										dc.w $206
										dc.l ms_map9_flag206
										dc.w $FFFD
										dc.w $A
										dc.l ms_map10
										dc.w $2D2
										dc.l ms_map10_flag2D2
										dc.w $FFFD
										dc.w $B
										dc.l ms_map11
										dc.w $FFFD
										dc.w $C
										dc.l ms_map12
										dc.w $FFFD
										dc.w $D
										dc.l ms_map13
										dc.w $2C6
										dc.l ms_map13_flag2C6
										dc.w $31F
										dc.l ms_map13_flag31F
										dc.w $201
										dc.l ms_map13_flag201
										dc.w $FFFD
										dc.w $E
										dc.l ms_map14
										dc.w $1CA
										dc.l ms_map14_flag1CA
										dc.w $FFFD
										dc.w $F
										dc.l ms_map15
										dc.w $212
										dc.l ms_map15_flag212
										dc.w $FFFD
										dc.w $10
										dc.l ms_map16
										dc.w $297
										dc.l ms_map16_flag297
										dc.w $212
										dc.l ms_map16_flag212
										dc.w $FFFD
										dc.w $11
										dc.l ms_map17
										dc.w $1F9
										dc.l ms_map17_flag1F9
										dc.w $212
										dc.l ms_map17_flag212
										dc.w $FFFD
										dc.w $12
										dc.l ms_map18
										dc.w $212
										dc.l ms_map18_flag212
										dc.w $FFFD
										dc.w $13
										dc.l ms_map19
										dc.w $1F5
										dc.l ms_map19_flag1F5
										dc.w $261
										dc.l ms_map19_flag261
										dc.w $1FA
										dc.l ms_map19_flag1FA
										dc.w $1FB
										dc.l ms_map19_flag1FB
										dc.w $21F
										dc.l ms_map19_flag21F
										dc.w $3D6
										dc.l ms_map19_flag3D6
										dc.w $FFFD
										dc.w $14
										dc.l ms_map20
										dc.w $1F5
										dc.l ms_map20_flag1F5
										dc.w $261
										dc.l ms_map20_flag261
										dc.w $1FA
										dc.l ms_map20_flag1FA
										dc.w $21F
										dc.l ms_map20_flag21F
										dc.w $FFFD
										dc.w $15
										dc.l ms_map21
										dc.w $1F5
										dc.l ms_map21_flag1F5
										dc.w $261
										dc.l ms_map21_flag261
										dc.w $1FA
										dc.l ms_map21_flag1FA
										dc.w $21F
										dc.l ms_map21_flag21F
										dc.w $FFFD
										dc.w $16
										dc.l ms_map22
										dc.w $20A
										dc.l ms_map22_flag20A
										dc.w $FFFD
										dc.w $17
										dc.l ms_map23
										dc.w $2FA
										dc.l ms_map23_flag2FA
										dc.w $FFFD
										dc.w $18
										dc.l ms_map24
										dc.w $FFFD
										dc.w $19
										dc.l ms_map25
										dc.w $FFFD
										dc.w $1A
										dc.l ms_map26
										dc.w $FFFD
										dc.w $1B
										dc.l ms_map27
										dc.w $20B
										dc.l ms_map27_flag20B
										dc.w $FFFD
										dc.w $1C
										dc.l ms_map28
										dc.w $FFFD
										dc.w $1D
										dc.l ms_map29
										dc.w $FFFD
										dc.w $1E
										dc.l ms_map30
										dc.w $311
										dc.l ms_map30_flag311
										dc.w $2F9
										dc.l ms_map30_flag2F9
										dc.w $FFFD
										dc.w $1F
										dc.l ms_map31
										dc.w $33E
										dc.l ms_map31_flag33E
										dc.w $FFFD
										dc.w $21
										dc.l ms_map33_flag16
										dc.w $20B
										dc.l ms_map33_flag20B
										dc.w $30F
										dc.l ms_map33_flag16
										dc.w $310
										dc.l ms_map33_flag310
										dc.w $312
										dc.l ms_map33_flag312
										dc.w $16
										dc.l ms_map33_flag16
										dc.w $FFFD
										dc.w $22
										dc.l ms_map34
										dc.w $310
										dc.l ms_map34_flag310
										dc.w $FFFD
										dc.w $24
										dc.l ms_map36
										dc.w $212
										dc.l ms_map36_flag212
										dc.w $FFFD
										dc.w $25
										dc.l ms_map37
										dc.w $3E7
										dc.l ms_map37_flag3E7
										dc.w $FFFD
										dc.w $26
										dc.l ms_map38
										dc.w $FFFD
										dc.w $27
										dc.l ms_map39
										dc.w $33E
										dc.l ms_map39_flag33E
										dc.w $FFFD
										dc.w $28
										dc.l ms_map40_flag1FB
										dc.w $1FA
										dc.l ms_map40_flag1FA
										dc.w $1FB
										dc.l ms_map40_flag1FB
										dc.w $FFFD
										dc.w $29
										dc.l ms_map41
										dc.w $FFFD
										dc.w $2A
										dc.l ms_map42
										dc.w $FFFD
										dc.w $2B
										dc.l ms_map43
										dc.w $264
										dc.l ms_map43_flag264
										dc.w $FFFD
										dc.w $2C
										dc.l ms_map44
										dc.w $261
										dc.l ms_map44_flag261
										dc.w $1FA
										dc.l ms_map44_flag1FA
										dc.w $1FB
										dc.l ms_map44_flag1FB
										dc.w $FFFD
										dc.w $2D
										dc.l ms_map45
										dc.w $FFFD
										dc.w $2E
										dc.l ms_map46
										dc.w $FFFD
										dc.w $33
										dc.l ms_map51
										dc.w $208
										dc.l ms_map51_flag208
										dc.w $FFFD
										dc.w $34
										dc.l ms_map52
										dc.w $200
										dc.l ms_map52_flag200
										dc.w $FFFD
										dc.w $37
										dc.l ms_map55
										dc.w $FFFD
										dc.w $38
										dc.l ms_map56
										dc.w $FFFD
										dc.w $3B
										dc.l ms_map59
										dc.w $21F
										dc.l ms_map59_flag21F
										dc.w $FFFD
										dc.w $3D
										dc.l ms_map61
										dc.w $2D9
										dc.l ms_map61_flag2D9
										dc.w $FFFD
										dc.w $3E
										dc.l ms_map62
										dc.w $4D
										dc.l ms_map62_flag4D
										dc.w $FFFD
										dc.w $3F
										dc.l ms_map63
										dc.w $1D
										dc.l ms_map63_flag1D
										dc.w $FFFD
										dc.w 0
										dc.l ms_map0
										dc.w $FFFD
										dc.w 1
										dc.l ms_map1
										dc.w $FFFD
										dc.w 2
										dc.l ms_map2
										dc.w $212
										dc.l ms_map2_flag212
										dc.w $FFFD
										dc.w $42
										dc.l ms_map66
										dc.w $FFFD
										dc.w $43
										dc.l ms_map67
										dc.w $FFFD
										dc.w $44
										dc.l ms_map68
										dc.w $FFFD
										dc.w $45
										dc.l ms_map69
										dc.w $FFFD
										dc.w $46
										dc.l ms_map70
										dc.w $FFFD
										dc.w $48
										dc.l ms_map72
										dc.w $FFFD
										dc.w $49
										dc.l ms_map73
										dc.w $FFFD
										dc.w $4A
										dc.l ms_map74
										dc.w $FFFD
										dc.w $4B
										dc.l ms_map75
										dc.w $FFFD
										dc.w $4C
										dc.l ms_map76
										dc.w $FFFD
										dc.w $4D
										dc.l ms_map77
										dc.w $FFFD
										dc.w $FFFF
