
; SCRIPT SECTION mapsetups\mapsetupstable :
; Map setups table
MapSetups:          dc.w 3                  ; list of map event addresses and flags to check
										dc.l off_50AE8
										dc.w $261
										dc.l off_50B00
										dc.w $1FA
										dc.l off_50B18
										dc.w $21F
										dc.l off_626A6
										dc.w $FFFD
										dc.w 4                  ; for map 4
										dc.l off_516CC
										dc.w $FFFD
										dc.w 5                  ; map 5
										dc.l off_51912
										dc.w $28A
										dc.l off_5192A
										dc.w $212
										dc.l off_603AE
										dc.w $1C
										dc.l off_603C6
										dc.w $FFFD
										dc.w 6
										dc.l off_54756
										dc.w $2BD
										dc.l off_5476E
										dc.w $2BE
										dc.l off_5473E
										dc.w $FFFD
										dc.w 7
										dc.l off_5537E
										dc.w $2BD
										dc.l off_55396
										dc.w $2BE
										dc.l off_5537E
										dc.w $325
										dc.l off_553AE
										dc.w $FFFD
										dc.w 8
										dc.l off_55FA6
										dc.w $2C4
										dc.l off_55F8E
										dc.w $FFFD
										dc.w 9
										dc.l off_56636
										dc.w $206
										dc.l off_5664E
										dc.w $FFFD
										dc.w $A
										dc.l off_56B84
										dc.w $2D2
										dc.l off_56B9C
										dc.w $FFFD
										dc.w $B
										dc.l off_579CA
										dc.w $FFFD
										dc.w $C
										dc.l off_57CCC
										dc.w $FFFD
										dc.w $D
										dc.l off_57E36
										dc.w $2C6
										dc.l off_57E4E
										dc.w $31F
										dc.l off_57E66
										dc.w $201
										dc.l off_57E7E
										dc.w $FFFD
										dc.w $E
										dc.l off_58E18
										dc.w $1CA
										dc.l off_58E30
										dc.w $FFFD
										dc.w $F
										dc.l off_5CDFE
										dc.w $212
										dc.l off_5CE16
										dc.w $FFFD
										dc.w $10
										dc.l off_51C76
										dc.w $297
										dc.l off_51C5E
										dc.w $212
										dc.l off_60FAE
										dc.w $FFFD
										dc.w $11
										dc.l off_52284
										dc.w $1F9
										dc.l off_5229C
										dc.w $212
										dc.l off_611A6
										dc.w $FFFD
										dc.w $12
										dc.l off_52A80
										dc.w $212
										dc.l off_6121A
										dc.w $FFFD
										dc.w $13
										dc.l off_52B4A
										dc.w $1F5
										dc.l off_52B62
										dc.w $261
										dc.l off_52B7A
										dc.w $1FA
										dc.l off_52B92
										dc.w $1FB
										dc.l off_52BAA
										dc.w $21F
										dc.l off_6299A
										dc.w $3D6
										dc.l off_629B2
										dc.w $FFFD
										dc.w $14
										dc.l off_53634
										dc.w $1F5
										dc.l off_5364C
										dc.w $261
										dc.l off_53664
										dc.w $1FA
										dc.l off_5367C
										dc.w $21F
										dc.l off_631EA
										dc.w $FFFD
										dc.w $15
										dc.l off_53E18
										dc.w $1F5
										dc.l off_53E30
										dc.w $261
										dc.l off_53E48
										dc.w $1FA
										dc.l off_53E60
										dc.w $21F
										dc.l off_6343C
										dc.w $FFFD
										dc.w $16
										dc.l off_592E0
										dc.w $20A
										dc.l off_592F8
										dc.w $FFFD
										dc.w $17
										dc.l off_59AC0
										dc.w $2FA
										dc.l off_59AD8
										dc.w $FFFD
										dc.w $18
										dc.l off_59C06
										dc.w $FFFD
										dc.w $19
										dc.l off_5D1CA
										dc.w $FFFD
										dc.w $1A
										dc.l off_59D08
										dc.w $FFFD
										dc.w $1B
										dc.l off_59F42
										dc.w $20B
										dc.l off_59F5A
										dc.w $FFFD
										dc.w $1C
										dc.l off_5F34C
										dc.w $FFFD
										dc.w $1D
										dc.l off_5A09E
										dc.w $FFFD
										dc.w $1E
										dc.l off_5A176
										dc.w $311
										dc.l off_5A18E
										dc.w $2F9
										dc.l off_5A1A6
										dc.w $FFFD
										dc.w $1F
										dc.l off_5D40E
										dc.w $33E
										dc.l off_5D426
										dc.w $FFFD
										dc.w $21
										dc.l off_5A646
										dc.w $20B
										dc.l off_5A65E
										dc.w $30F
										dc.l off_5A646
										dc.w $310
										dc.l off_5A676
										dc.w $312
										dc.l off_5A68E
										dc.w $16
										dc.l off_5A646
										dc.w $FFFD
										dc.w $22
										dc.l off_5B5B6
										dc.w $310
										dc.l off_5B5CE
										dc.w $FFFD
										dc.w $24
										dc.l off_5D756
										dc.w $212
										dc.l off_5D76E
										dc.w $FFFD
										dc.w $25
										dc.l off_5F630
										dc.w $3E7
										dc.l off_5F660
										dc.w $FFFD
										dc.w $26
										dc.l off_5DAE4
										dc.w $FFFD
										dc.w $27
										dc.l off_5DF84
										dc.w $33E
										dc.l off_5DF9C
										dc.w $FFFD
										dc.w $28
										dc.l off_53F60
										dc.w $1FA
										dc.l off_53F48
										dc.w $1FB
										dc.l off_53F60
										dc.w $FFFD
										dc.w $29
										dc.l off_5F3E8
										dc.w $FFFD
										dc.w $2A
										dc.l off_5FDE4
										dc.w $FFFD
										dc.w $2B
										dc.l off_53FFE
										dc.w $264
										dc.l off_54016
										dc.w $FFFD
										dc.w $2C
										dc.l off_54348
										dc.w $261
										dc.l off_54360
										dc.w $1FA
										dc.l off_54378
										dc.w $1FB
										dc.l off_54390
										dc.w $FFFD
										dc.w $2D
										dc.l off_5FF62
										dc.w $FFFD
										dc.w $2E
										dc.l off_5BFEE
										dc.w $FFFD
										dc.w $33
										dc.l off_5C27C
										dc.w $208
										dc.l off_5C294
										dc.w $FFFD
										dc.w $34
										dc.l off_5C454
										dc.w $200
										dc.l off_5C46C
										dc.w $FFFD
										dc.w $37
										dc.l off_5E22C
										dc.w $FFFD
										dc.w $38
										dc.l off_61488
										dc.w $FFFD
										dc.w $3B
										dc.l off_5EAA8
										dc.w $21F
										dc.l off_6153E
										dc.w $FFFD
										dc.w $3D
										dc.l off_5C650
										dc.w $2D9
										dc.l off_5C638
										dc.w $FFFD
										dc.w $3E
										dc.l off_5C76A
										dc.w $4D
										dc.l off_5C782
										dc.w $FFFD
										dc.w $3F
										dc.l off_5C968
										dc.w $1D
										dc.l off_5C950
										dc.w $FFFD
										dc.w 0
										dc.l off_5E37C
										dc.w $FFFD
										dc.w 1
										dc.l off_5E62A
										dc.w $FFFD
										dc.w 2
										dc.l off_5E86C
										dc.w $212
										dc.l off_5E884
										dc.w $FFFD
										dc.w $42
										dc.l off_4FA70
										dc.w $FFFD
										dc.w $43
										dc.l off_4FAEC
										dc.w $FFFD
										dc.w $44
										dc.l off_4FD4C
										dc.w $FFFD
										dc.w $45
										dc.l off_4FD88
										dc.w $FFFD
										dc.w $46
										dc.l off_4FDE4
										dc.w $FFFD
										dc.w $48
										dc.l off_4FE44
										dc.w $FFFD
										dc.w $49
										dc.l off_50312
										dc.w $FFFD
										dc.w $4A
										dc.l off_5096A
										dc.w $FFFD
										dc.w $4B
										dc.l off_509D8
										dc.w $FFFD
										dc.w $4C
										dc.l off_50A0A
										dc.w $FFFD
										dc.w $4D
										dc.l off_50A50
										dc.w $FFFD
										dc.w $FFFF
