
; SCRIPT SECTION maps\entries\map59\mapsetups\s1_21F :
; 
ms_map59_flag21F_Entities:
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $B2
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $AD
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 2
										dc.b $AB
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 2
										dc.b $AD
										dc.l eas_Init           
										dc.b $B
										dc.b $F
										dc.b 1
										dc.b $CC
										dc.l eas_Init           
										dc.b $E
										dc.b $B
										dc.b 1
										dc.b 7
										dc.l eas_Init           
										dc.b $B
										dc.b $A
										dc.b 0
										dc.b $1C
										dc.l eas_Init           
										dc.b $F
										dc.b $A
										dc.b 2
										dc.b $D1
										dc.l eas_Init           
										dc.b $D
										dc.b 9
										dc.b 2
										dc.b $D6
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $D7
										dc.l eas_Init2          
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b $C3
										dc.l eas_Init           
										dc.w $FFFF
