
; SCRIPT SECTION mapsetups\map03\s1_21F :
; 
ms_map3_flag21F_Entities:
										dc.b 4
										dc.b $A
										dc.b 0
										dc.b $C3
										dc.l eas_Init           
										dc.b 5
										dc.b $A
										dc.b 2
										dc.b $CA
										dc.l eas_Init           
										dc.b $13
										dc.b $E
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b $13
										dc.b $E
										dc.b 3
										dc.b $A
										dc.b $17
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $14
										dc.b $15
										dc.b 3
										dc.b $C9
										dc.b $FF
										dc.b $14
										dc.b $15
										dc.b 1
										dc.b $1A
										dc.b 9
										dc.b 1
										dc.b $C9
										dc.l eas_Init           
										dc.b $2D
										dc.b $12
										dc.b 1
										dc.b $EA
										dc.l eas_Init           
										dc.b $1A
										dc.b $1B
										dc.b 3
										dc.b $C3
										dc.l eas_Init           
										dc.b $17
										dc.b $1B
										dc.b 3
										dc.b $C2
										dc.l eas_Init           
										dc.b 1
										dc.b $1A
										dc.b 0
										dc.b $CE
										dc.l eas_Init           
										dc.b $2A
										dc.b 9
										dc.b 3
										dc.b $D1
										dc.l eas_Init           
										dc.b $2C
										dc.b $A
										dc.b 0
										dc.b 1
										dc.l eas_Init           
										dc.b $2B
										dc.b $B
										dc.b 2
										dc.b 2
										dc.l eas_Init           
										dc.b $28
										dc.b $B
										dc.b 1
										dc.b 3
										dc.l eas_Init           
										dc.b $28
										dc.b $A
										dc.b 3
										dc.b 4
										dc.l eas_Init           
										dc.w $FFFF
