
; SCRIPT SECTION mapsetups\map03\s1_261 :
; 
ms_map3_flag261_Entities:
										dc.b 6
										dc.b 9
										dc.b 0
										dc.b $C3
										dc.l eas_Init           
										dc.b $C
										dc.b 9
										dc.b 0
										dc.b $C6
										dc.b $FF
										dc.b $C
										dc.b 9
										dc.b 1
										dc.b $E
										dc.b 9
										dc.b 1
										dc.b $C7
										dc.l eas_Init           
										dc.b 7
										dc.b $12
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b 9
										dc.b $17
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b 1
										dc.b $17
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $10
										dc.b $16
										dc.b 3
										dc.b $C5
										dc.b $FF
										dc.b $10
										dc.b $16
										dc.b 2
										dc.b $D
										dc.b $13
										dc.b 3
										dc.b $C7
										dc.l eas_Init           
										dc.b $1B
										dc.b $D
										dc.b 2
										dc.b $C7
										dc.l eas_Init           
										dc.b $19
										dc.b $D
										dc.b 0
										dc.b $C3
										dc.l eas_Init           
										dc.b $1B
										dc.b 3
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $1F
										dc.b 3
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $17
										dc.b $15
										dc.b 3
										dc.b $CA
										dc.l eas_Init           
										dc.b $1D
										dc.b $18
										dc.b 1
										dc.b $C8
										dc.l eas_Init           
										dc.b $20
										dc.b $1B
										dc.b 3
										dc.b $EB
										dc.b $FF
										dc.b $20
										dc.b $1B
										dc.b 1
										dc.b $27
										dc.b $1A
										dc.b 3
										dc.b $CA
										dc.b $FF
										dc.b $27
										dc.b $1A
										dc.b 1
										dc.b $25
										dc.b $15
										dc.b 3
										dc.b $C3
										dc.l eas_Init           
										dc.b $2F
										dc.b $18
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b $2F
										dc.b $18
										dc.b 2
										dc.b $19
										dc.b $16
										dc.b 3
										dc.b $DC
										dc.b $FF
										dc.b $19
										dc.b $16
										dc.b 1
										dc.b $1A
										dc.b $16
										dc.b 3
										dc.b $DE
										dc.b $FF
										dc.b $1A
										dc.b $16
										dc.b 1
										dc.b $1B
										dc.b $16
										dc.b 3
										dc.b 6
										dc.b $FF
										dc.b $1B
										dc.b $16
										dc.b 1
										dc.b $20
										dc.b $B
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b $1D
										dc.b 7
										dc.b 3
										dc.b $C4
										dc.b $FF
										dc.b $1D
										dc.b 7
										dc.b 1
										dc.b $12
										dc.b $E
										dc.b 3
										dc.b $C8
										dc.b $FF
										dc.b $12
										dc.b $E
										dc.b 1
										dc.b $12
										dc.b 9
										dc.b 3
										dc.b $C3
										dc.l eas_Init           
										dc.b $14
										dc.b $10
										dc.b 3
										dc.b $E2
										dc.b $FE
										dc.b 5
										dc.b $C
										dc.b $AC
										dc.b 8
										dc.b $12
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b 1
										dc.b $1D
										dc.b 1
										dc.b 3
										dc.l eas_Init           
										dc.w $FFFF
										dc.b   3
										dc.b   3
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   0
										dc.b   1
										dc.b   1
										dc.b   2
										dc.b   1
										dc.b   2
										dc.b   2
										dc.b   2
										dc.b   1
										dc.b   2
										dc.b   2
										dc.b   2
										dc.b   2
										dc.b   2
										dc.b   3
										dc.b   2
										dc.b   3
										dc.b $FF
										dc.b $FF
