
; SCRIPT SECTION mapsetups\map15\s1 :
; 
ms_map15_Entities:  dc.b $1B
										dc.b $1B
										dc.b 3
										dc.b $DA
										dc.b $FF
										dc.b $1B
										dc.b $1B
										dc.b 1
										dc.b $F
										dc.b $1B
										dc.b 3
										dc.b $DC
										dc.b $FF
										dc.b $F
										dc.b $1B
										dc.b 1
										dc.b $1D
										dc.b $D
										dc.b 2
										dc.b $DE
										dc.l eas_Init           
										dc.b $14
										dc.b $E
										dc.b 3
										dc.b $E2
										dc.l eas_Init           
										dc.b $1A
										dc.b $F
										dc.b 3
										dc.b $DD
										dc.b $FF
										dc.b $1A
										dc.b $F
										dc.b 2
										dc.b $C
										dc.b $1A
										dc.b 1
										dc.b $E0
										dc.l eas_Init           
										dc.b 6
										dc.b $10
										dc.b 3
										dc.b $DF
										dc.b $FF
										dc.b 6
										dc.b $10
										dc.b 2
										dc.b $1C
										dc.b 6
										dc.b 3
										dc.b $E1
										dc.b $FF
										dc.b $1C
										dc.b 6
										dc.b 2
										dc.b $1F
										dc.b $D
										dc.b 1
										dc.b $DB
										dc.b $FF
										dc.b $1F
										dc.b $D
										dc.b 1
										dc.b 3
										dc.b $17
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.b $C
										dc.b $F
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.b 2
										dc.b $17
										dc.b 3
										dc.b $C1
										dc.l eas_Init           
										dc.w $FFFF
