
; SCRIPT SECTION mapsetups\map19\s1_261 :
; 
ms_map19_flag261_Entities:
										dc.b $1B
										dc.b $D
										dc.b 0
										dc.b $CF
										dc.l eas_Init           
										dc.b $1F
										dc.b $D
										dc.b 2
										dc.b $CF
										dc.l eas_Init           
										dc.b $18
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $18
										dc.b $1A
										dc.b 1
										dc.b $1E
										dc.b $1B
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $1E
										dc.b $1B
										dc.b 1
										dc.b $D
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Motionless     
										dc.b $E
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $1D
										dc.b $12
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $1D
										dc.b $12
										dc.b 2
										dc.b $18
										dc.b $10
										dc.b 0
										dc.b $D0
										dc.l eas_Init           
										dc.b $12
										dc.b $A
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $22
										dc.b $14
										dc.b 3
										dc.b $C2
										dc.b $FF
										dc.b $22
										dc.b $14
										dc.b 1
										dc.b $1D
										dc.b 7
										dc.b 3
										dc.b $CD
										dc.l eas_Init           
										dc.b $1F
										dc.b 6
										dc.b 3
										dc.b $C6
										dc.l eas_Init           
										dc.b $1D
										dc.b 6
										dc.b 3
										dc.b $CB
										dc.l eas_Init           
										dc.w $FFFF
