
; SCRIPT SECTION maps\entries\map16\mapsetups\s1 :
; 
ms_map16_Entities:  dc.b $10
										dc.b $F
										dc.b 3
										dc.b $1C
										dc.l eas_Init           
										dc.b $11
										dc.b $10
										dc.b 3
										dc.b $D6
										dc.l eas_Init           
										dc.b $F
										dc.b $12
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $10
										dc.b $12
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $12
										dc.b $12
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $13
										dc.b $12
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $F
										dc.b $13
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $10
										dc.b $13
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $12
										dc.b $13
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $13
										dc.b $13
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $F
										dc.b $14
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $10
										dc.b $14
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $12
										dc.b $14
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $13
										dc.b $14
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $F
										dc.b $15
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $10
										dc.b $15
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $12
										dc.b $15
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b $13
										dc.b $15
										dc.b 1
										dc.b $CE
										dc.l eas_Init           
										dc.b 3
										dc.b $17
										dc.b 1
										dc.b $42
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $78
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $43
										dc.l eas_Init           
										dc.b $1B
										dc.b 5
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.w $FFFF
