
; SCRIPT SECTION maps\entries\map19\mapsetups\s1 :
; 
ms_map19_Entities:  dc.b $19
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $19
										dc.b $1A
										dc.b 2
										dc.b $1A
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $1A
										dc.b $1A
										dc.b 2
										dc.b $11
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $E
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $F
										dc.b $14
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $F
										dc.b $14
										dc.b 1
										dc.b $1C
										dc.b $11
										dc.b 3
										dc.b $CF
										dc.l eas_Init           
										dc.b $1E
										dc.b $11
										dc.b 3
										dc.b $CF
										dc.l eas_Init           
										dc.b $1D
										dc.b 8
										dc.b 3
										dc.b $C6
										dc.l eas_46246          
										dc.b $18
										dc.b $10
										dc.b 3
										dc.b $D0
										dc.l eas_Init           
										dc.b $14
										dc.b $11
										dc.b 3
										dc.b $C3
										dc.b $FF
										dc.b $14
										dc.b $11
										dc.b 1
										dc.b $13
										dc.b 5
										dc.b 3
										dc.b $CE
										dc.l eas_Init           
										dc.b $15
										dc.b 4
										dc.b 3
										dc.b $D0
										dc.l eas_Init           
										dc.b $10
										dc.b 5
										dc.b 3
										dc.b $D1
										dc.l eas_Init           
										dc.w $FFFF
