
; SCRIPT SECTION maps\entries\map19\mapsetups\s1_1FA :
; 
ms_map19_flag1FA_Entities:
										dc.b $13
										dc.b $A
										dc.b 0
										dc.b $1C
										dc.l eas_Init           
										dc.b $19
										dc.b $D
										dc.b 2
										dc.b $D1
										dc.l eas_Init           
										dc.b $1A
										dc.b $C
										dc.b 2
										dc.b $CD
										dc.l eas_Init           
										dc.b $1A
										dc.b $D
										dc.b 2
										dc.b $CB
										dc.l eas_Init           
										dc.b $13
										dc.b $B
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $12
										dc.b $B
										dc.b 0
										dc.b $CE
										dc.l eas_Init           
										dc.b $12
										dc.b $A
										dc.b 0
										dc.b $CE
										dc.l eas_Init           
										dc.b $19
										dc.b $A
										dc.b 3
										dc.b $C6
										dc.l eas_Init           
										dc.b $1B
										dc.b $B
										dc.b 2
										dc.b $D0
										dc.l eas_Init           
										dc.b $1C
										dc.b $C
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $1C
										dc.b $D
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $1C
										dc.b $10
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $1B
										dc.b $12
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $1E
										dc.b $13
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $1F
										dc.b $13
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $1C
										dc.b $14
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $1D
										dc.b $15
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $1B
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $1D
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $1D
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $F
										dc.b $13
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $E
										dc.b $14
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $F
										dc.b $14
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.b $E
										dc.b $15
										dc.b 3
										dc.b $CE
										dc.l eas_LyingRightBis  
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $C3
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $CC
										dc.l eas_Init           
										dc.b $1C
										dc.b $E
										dc.b 3
										dc.b $CE
										dc.l eas_LyingLeftBis   
										dc.w $FFFF
