
; SCRIPT SECTION maps\entries\map19\mapsetups\s1_21F :
; 
ms_map19_flag21F_Entities:
										dc.b $1A
										dc.b $B
										dc.b 0
										dc.b 5
										dc.l eas_Init           
										dc.b $20
										dc.b $A
										dc.b 2
										dc.b 7
										dc.l eas_Init           
										dc.b $1A
										dc.b $A
										dc.b 0
										dc.b 8
										dc.l eas_Init           
										dc.b $1A
										dc.b $D
										dc.b 0
										dc.b $B
										dc.l eas_Init           
										dc.b $20
										dc.b $B
										dc.b 2
										dc.b $A
										dc.l eas_Init           
										dc.b $20
										dc.b $C
										dc.b 2
										dc.b $13
										dc.l eas_Init           
										dc.b $1A
										dc.b $C
										dc.b 0
										dc.b $19
										dc.l eas_Init           
										dc.b $20
										dc.b $D
										dc.b 2
										dc.b $1B
										dc.l eas_Init           
										dc.b $19
										dc.b $D
										dc.b 0
										dc.b $1A
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 0
										dc.b 1
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 2
										dc.b 2
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 1
										dc.b 3
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b 4
										dc.l eas_Init           
										dc.b $1D
										dc.b 6
										dc.b 3
										dc.b $CB
										dc.l eas_Init           
										dc.b $3F
										dc.b $3F
										dc.b 3
										dc.b $D1
										dc.l eas_Init           
										dc.b $18
										dc.b $10
										dc.b 0
										dc.b $C7
										dc.l eas_Init           
										dc.b $17
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $17
										dc.b $1A
										dc.b 2
										dc.b $22
										dc.b $1A
										dc.b 3
										dc.b $CE
										dc.b $FF
										dc.b $22
										dc.b $1A
										dc.b 2
										dc.b $E
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Init3          
										dc.b $11
										dc.b $19
										dc.b 3
										dc.b $CE
										dc.l eas_Init3          
										dc.w $FFFF
