
; SCRIPT SECTION maps\entries\map36\mapsetups\s1 :
; 
ms_map36_Entities:  dc.b $1C
										dc.b 6
										dc.b 3
										dc.b $16
										dc.l eas_Init           
										dc.b $12
										dc.b $18
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $12
										dc.b $18
										dc.b 1
										dc.b $21
										dc.b $1A
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b 7
										dc.b 5
										dc.b 0
										dc.b $E9
										dc.l eas_Init           
										dc.b 4
										dc.b $16
										dc.b 0
										dc.b $E9
										dc.l eas_Init           
										dc.b $15
										dc.b $10
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $15
										dc.b $10
										dc.b 1
										dc.b $1F
										dc.b 5
										dc.b 2
										dc.b $E9
										dc.l eas_Init           
										dc.b $1F
										dc.b $A
										dc.b 3
										dc.b $E9
										dc.b $FF
										dc.b $1F
										dc.b $A
										dc.b 1
										dc.b $1D
										dc.b 3
										dc.b 3
										dc.b $E7
										dc.l eas_Init           
										dc.b $26
										dc.b 5
										dc.b 3
										dc.b $E8
										dc.l eas_Init           
										dc.b $10
										dc.b $A
										dc.b 3
										dc.b $EA
										dc.b $FF
										dc.b $10
										dc.b $A
										dc.b 1
										dc.b $16
										dc.b 9
										dc.b 3
										dc.b $EA
										dc.l eas_Init           
										dc.b $28
										dc.b 4
										dc.b 3
										dc.b $C0
										dc.l eas_Init           
										dc.w $FFFF
